### ISSUE TITLE
Feature Request: Always on Top

### ISSUE THREAD

**Issue by willstall** [patriciogonzalezvivo/glslViewer#108]
I would absolutely love to request an always on top feature for osX ( not sure if it's there on win ). 

Having tried out the pi edition, it's amazing having glslViewer just running in the corner. It would be great to do that in an environment of choice. Could be the same -l flag.

**Comment by patriciogonzalezvivo** [comment]
Nice idea! I will investigate if it's possible

**Comment by patriciogonzalezvivo** [comment]
Done! that was an easy one! compile from source and give it a run

**Comment by willstall** [comment]
dudeeeee....this is fantastic. Thank you so much! Also, huge fan =)

**Comment by willstall** [comment]
Also, threw a tip your way....cause The Book of Shaders changed my life.

**Comment by patriciogonzalezvivo** [comment]
: D
I'm so happy to hear that! I'm very passionate about GLSL language and GPU architecture, and writing that book also change mine : ) allowing me to do more of what I love. Sharing multiplies, expand and give back. I just wish I could have more free time to finish it : /
Thanks you for your nice words!
