### ISSUE TITLE
Error compiling from sources

### ISSUE THREAD

**Issue by gerardogc2378** [patriciogonzalezvivo/glslViewer#109]
OS: ArchLinux

$ make
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/include/libdrm  include/rgbe/rgbe.cc include/tinyobjloader/tiny_obj_loader.cc src/window.o src/main.o src/sandbox.o src/gl/vertexLayout.o src/gl/textureCube.o src/gl/fbo.o src/gl/texture.o src/gl/shader.o src/gl/pingpong.o src/gl/vbo.o src/ui/cursor.o src/tools/fs.o src/tools/geom.o src/tools/text.o src/tools/uniform.o src/tools/pixels.o src/3d/node.o src/3d/camera.o src/types/mesh.o src/types/polyline.o src/types/polarPoint.o src/types/rectangle.o src/types/shapes.o -lglfw -lGLU -lGL -lXrandr -lXi -lXxf86vm -lXcursor -lXinerama -lXrender -lX11 -lXext -lXdamage -lXfixes  -lpthread -ldl -rdynamic -o bin/glslViewer
/usr/bin/ld: src/gl/pingpong.o: in function `PingPong::allocate(int, int, bool)':
/home/ggc/tmp/glslViewer/src/gl/pingpong.cpp:12: undefined reference to `Fbo::allocate(unsigned int, unsigned int, bool)'
/usr/bin/ld: /home/ggc/tmp/glslViewer/src/gl/pingpong.cpp:12: undefined reference to `Fbo::allocate(unsigned int, unsigned int, bool)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:64: bin/glslViewer] Error 1

**Comment by patriciogonzalezvivo** [comment]
Mmm  that's odd. Could you try:

```bash
git pull
git check master
make clean
make
```

**Comment by gerardogc2378** [comment]
Thanks, it is working now!

**Comment by patriciogonzalezvivo** [comment]
Cool! I'm glad it worked out. For next time, don't forget to clean before compiling ; )
