### ISSUE TITLE
Feature Request: Camera Texture Uniforms

### ISSUE THREAD

**Issue by willstall** [patriciogonzalezvivo/glslViewer#110]
I realize this might be a rather large feature request, but it would be amazing to be able to get a live texture from a camera(actual video camera, not world space camera) if present and enabled on device.

**Comment by patriciogonzalezvivo** [comment]
that would be awesome. I have been thinking how to have a video in in glslViewer for a long time. But a cross platform solution between osx and linux (that also works on Rpi) it's tricky.

**Comment by willstall** [comment]
just for fun...something stupid I've been playing with:
https://willstall.github.io/fringe2018/three/video_fbm.html

took me way too long to figure out how to get camera access in the web *facepalm*

**Comment by techguy1** [comment]
@patriciogonzalezvivo Your GLSL project is a very great work.
I think video format or camera hardware support would be a overkill for this project.
But a similar feature like "sequence,<A_sec>,<B_sec>" for the output of png's to also have a sequence of input png's would be a great feature. 
Normally you would like to limit the fps on a life display.
But when you are in headless mode may be you would like to work with number of frames instead.

**Comment by patriciogonzalezvivo** [comment]
Added support foe capture devices, video files and stream urls. Check it here https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-video-support
