### ISSUE TITLE
Compilation on Ubuntu 18

### ISSUE THREAD

**Issue by rockcat** [patriciogonzalezvivo/glslViewer#111]
Hi

I'm having trouble building and running on Ubuntu 18.04
Can you confirm what compiler version you use?

Thanks

**Comment by patriciogonzalezvivo** [comment]
Hi. I can confirm that glslViewer compiles correctly on Ubuntu 18.04. Printing the compile error can help, until that please take a look to the documentation and note the comment on " Glfw3 library in Ubuntu 18.04 is causing trobles. For that you need to compile gldw3 from source (next paragraph) ..."

**Comment by rockcat** [comment]
Hi

I built glfw from source as suggested and had no issues there, 
Its a problem with strstr - it could me my setup which is why I wanted to check first.Here's the compiler output. I have also tried with gcc 7.3

paul@elderberry:~/workspace/glslViewer$ make clean
removed './bin/glslViewer'
removed 'src/main.o'
removed 'src/sandbox.o'
removed 'src/window.o'
removed 'src/3d/camera.o'
removed 'src/3d/node.o'
removed 'src/gl/fbo.o'
removed 'src/gl/pingpong.o'
removed 'src/gl/shader.o'
removed 'src/gl/texture.o'
removed 'src/gl/textureCube.o'
removed 'src/gl/vbo.o'
removed 'src/gl/vertexLayout.o'
removed 'src/tools/fs.o'
removed 'src/tools/geom.o'
removed 'src/tools/image.o'
removed 'src/tools/text.o'
removed 'src/tools/uniform.o'
removed 'src/types/mesh.o'
removed 'src/types/polarPoint.o'
removed 'src/types/polyline.o'
removed 'src/types/rectangle.o'
removed 'src/types/shapes.o'
paul@elderberry:~/workspace/glslViewer$ make -j8
src/window.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/window.cpp -o src/window.o -Wno-deprecated-declarations
src/main.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/main.cpp -o src/main.o -Wno-deprecated-declarations
src/sandbox.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/sandbox.cpp -o src/sandbox.o -Wno-deprecated-declarations
src/gl/vertexLayout.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/vertexLayout.cpp -o src/gl/vertexLayout.o -Wno-deprecated-declarations
src/gl/textureCube.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/textureCube.cpp -o src/gl/textureCube.o -Wno-deprecated-declarations
src/gl/fbo.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/fbo.cpp -o src/gl/fbo.o -Wno-deprecated-declarations
src/gl/texture.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/texture.cpp -o src/gl/texture.o -Wno-deprecated-declarations
src/gl/shader.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/shader.cpp -o src/gl/shader.o -Wno-deprecated-declarations
src/gl/pingpong.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/pingpong.cpp -o src/gl/pingpong.o -Wno-deprecated-declarations
src/gl/vbo.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/gl/vbo.cpp -o src/gl/vbo.o -Wno-deprecated-declarations
src/tools/image.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/tools/image.cpp -o src/tools/image.o -Wno-deprecated-declarations
src/tools/fs.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/tools/fs.cpp -o src/tools/fs.o -Wno-deprecated-declarations
src/tools/text.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/tools/text.cpp -o src/tools/text.o -Wno-deprecated-declarations
src/tools/uniform.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/tools/uniform.cpp -o src/tools/uniform.o -Wno-deprecated-declarations
src/tools/geom.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/tools/geom.cpp -o src/tools/geom.o -Wno-deprecated-declarations
src/3d/node.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/3d/node.cpp -o src/3d/node.o -Wno-deprecated-declarations
src/3d/camera.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_LINUX -I/usr/local/include -I/usr/include/libdrm -Isrc/ -Iinclude/ -g -c src/3d/camera.cpp -o src/3d/camera.o -Wno-deprecated-declarations
src/tools/text.cpp: In function ‘bool find_id(const string&, const char*)’:
src/tools/text.cpp:180:12: error: ‘strstr’ is not a member of ‘std’
     return std::strstr(program.c_str(), id) != 0;
            ^
src/tools/text.cpp:181:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:60: recipe for target 'src/tools/text.o' failed
make: *** [src/tools/text.o] Error 1
make: *** Waiting for unfinished jobs....
paul@elderberry:~/workspace/glslViewer$ gcc --version
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

paul@elderberry:~/workspace/glslViewer$

**Comment by rockcat** [comment]
Solved it - I was using g++ 4.8 and it wouldn't compile.
I changed to g++ 7.3 and it works fine.
When I tried this before I had changed my gcc version not my g++ version  - that was my mistake.
There is an issue with old compilers though so you might want to suggest a minimum g++ version
Thanks for this great work!

**Comment by patriciogonzalezvivo** [comment]
I'm glad it worked out! 

Thanks for your nice words!
