### ISSUE TITLE
Feature Request: fullscreen mode

### ISSUE THREAD

**Issue by noerw** [patriciogonzalezvivo/glslViewer#112]
Would be nice to have a fullscreen toggle (F11, alt+return, CLI flag?) for live coding or distraction free viewing.

Thanks for this great program!

**Comment by dwaindibbly** [comment]
in linux it's easy, `wmctl -r :SELECT: -b toggle,fullscreen` I think it is. you need to install `wmctl` if you haven't already, but that is only a workaround, on windows i have no idea what workaround to use.

**Comment by patriciogonzalezvivo** [comment]
Hi! I just add a `--fullscreen` or '-f' argument. So if you run:

```
glslViewer examples/3D/03_models/head.obj -f   
```

or 

```
glslViewer examples/3D/03_models/head.obj --fullscreen
```

You should execute glslViewer in fullscreen on all platforms
