### ISSUE TITLE
Question: How to render Model, Texture, Shaders

### ISSUE THREAD

**Issue by pr3ddi** [patriciogonzalezvivo/glslViewer#115]
What would be the command line to render an object (cube), some texture(s), and apply shaders?
Much appreciated, if someone could provide an working example.

pr3ddi

**Comment by patriciogonzalezvivo** [comment]
1. You need to make your own geometry on any program you like. 
2. Then export it as a .obj or .ply
3. Then do:
```bash
glslViewer your_shader.frag your_texture.png your_geometry.obj
```
you can change the order if you like
