### ISSUE TITLE
[question] auto loading within vscode

### ISSUE THREAD

**Issue by lewislepton** [patriciogonzalezvivo/glslViewer#116]
on trying this with vscode, im happy I can use that, rather than sublime. though I do love sublimes speed.

but unlike sublime, vscode can auto open. was just wondering if you have or would know of ways to do an auto open.

my idea was this, which ive been looking at:
• have the built-in terminal in vscode spit out its command to open glslViewer, with the name

only thing is recognising the file format. but im just trying some cheap tests just now

**Comment by patriciogonzalezvivo** [comment]
How it's this going? I also love sublime but I have myself enjoying vs code. Let me know if you work on a plugin that loads glslViewer : )
