### ISSUE TITLE
Better Usage Arguments On Help

### ISSUE THREAD

**Issue by excalith** [patriciogonzalezvivo/glslViewer#117]
Hello,

I am not sure if this was intentional but I think we could use line breaks for arguments of `usage`. They will all be within a line as you write command anyway, so line breaks will help look up args easily. I can split them to lines and send PR if you want.

Here is the blob:
https://github.com/patriciogonzalezvivo/glslViewer/blob/00bc728be75a6a33fcab65f85358211efabc4666/src/main.cpp#L63

**Comment by patriciogonzalezvivo** [comment]
that would be very helpful thanks you
