### ISSUE TITLE
Mojave version 10.14, glslViewer 1.5.6 - Black Screen 

### ISSUE THREAD

**Issue by willstall** [patriciogonzalezvivo/glslViewer#123]
Heyo!

I'm having the black screen issue when trying to load a fragment shader. I did remove and install glfw3 and do a make + make install. 

Strange enough, I did have the black screen go away after quite awhile while idle.

Probably an issue i'm having with install and not a bug, but throwing it in here just in case anyway.

Cheers!

**Comment by willstall** [comment]
whooaaaa....ok, the black screen is not able idle. If I move the window, black screen goes away.

**Comment by patriciogonzalezvivo** [comment]
Hi! 

Yes this is a well known bug produce by Apple. There is a special branch of GLFW with a WIP of the fix. Please read in the main Readme.md that there is a note for Mojave on the MacOS instructions.

**Comment by patriciogonzalezvivo** [comment]
@willstall did you find the instructions to recompile for Mojave? did that work for you?

All the best,


Patricio

**Comment by willstall** [comment]
Oh, I’d already found those before I posted. They didn’t work. But, the
moving does seem to work and it renders to headless fine too.

**Comment by patriciogonzalezvivo** [comment]
I believe this is solved
