### ISSUE TITLE
RPi stretch: error on make

### ISSUE THREAD

**Issue by undee123** [patriciogonzalezvivo/glslViewer#129]
Hi guys,

I've Raspbian Stretch installed and get these errors when I try to install glslViewer from source:
`root@raspberrypi:~/glslViewer# make

Platform Raspbian GNU/Linux 9 (stretch)

src/window.o
g++ -Wall -O3 -std=c++11 -fpermissive -DGLM_FORCE_CXX98 -DPLATFORM_RPI -Isrc/ -Iinclude/ -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/l                                             inux -g -c src/window.cpp -o src/window.o -Wno-deprecated-declarations
src/main.o
g++ -Wall -O3 -std=c++11 -fpermissive -DGLM_FORCE_CXX98 -DPLATFORM_RPI -Isrc/ -Iinclude/ -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/l                                             inux -g -c src/main.cpp -o src/main.o -Wno-deprecated-declarations
src/sandbox.o
g++ -Wall -O3 -std=c++11 -fpermissive -DGLM_FORCE_CXX98 -DPLATFORM_RPI -Isrc/ -Iinclude/ -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/l                                             inux -g -c src/sandbox.cpp -o src/sandbox.o -Wno-deprecated-declarations
src/sandbox.cpp: In member function ‘void Sandbox::onScreenshot(std::__cxx11::string)’:
src/sandbox.cpp:1043:23: error: ‘GL_READ_BUFFER’ was not declared in this scope
         glGetIntegerv(GL_READ_BUFFER, &currentBuffer);
                       ^~~~~~~~~~~~~~
src/sandbox.cpp:1045:30: error: ‘glReadBuffer’ was not declared in this scope
         glReadBuffer(GL_FRONT);
                              ^
Makefile:60: die Regel für Ziel „src/sandbox.o“ scheiterte
make: *** [src/sandbox.o] Fehler 1
`

Can't find out what's happening here :-(
Any hints?

Thank you very much!!!

**Comment by patriciogonzalezvivo** [comment]
Hi! I believe this is a regression introduce here https://github.com/patriciogonzalezvivo/glslViewer/commit/7ee4f503b87d481bdbe24e3d8bed9e18d7089567

Do you mind cloning the previus version and give it a try?

**Comment by patriciogonzalezvivo** [comment]
Ok... I temporally revert. Do you mind pulling the latest changes and recompiling?

**Comment by undee123** [comment]
Worked now, thank you very much!!!

**Comment by Wilhansen** [comment]
Hi! Do you guys know what’s the fastest/easiest way I can get glslviewer to compile/run/test in an RPi environment? I’ve got an unused RPi 2 lying around if that is needed?
