### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [patriciogonzalezvivo/glslViewer#131]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Shader](https://github.com/patriciogonzalezvivo/glslViewer/blob/6974cb46aaa33dca3b39aaffcd8e5cb75ce9153d/src/gl/shader.cpp#L18 "Destructor for Shader")
- [Vbo::setVertexLayout](https://github.com/patriciogonzalezvivo/glslViewer/blob/23a8ddfc7e3a43e6128691d8e6a796dbe071c851/src/gl/vbo.cpp#L23 "Vbo::setVertexLayout function")

**Comment by patriciogonzalezvivo** [comment]
Thanks
