### ISSUE TITLE
Bug/Feature - waitForSeconds sequence,5,10

### ISSUE THREAD

**Issue by willstall** [patriciogonzalezvivo/glslViewer#132]
Heyo!

I love glslViewer as you're aware and use it for all my dallies. I'd love to start using buffers, but as of now. I cannot seem to get glslViewer to run the shader for a few seconds before it does it's sequencing. 

Let's use the example of a 5 second sequence using a buffer. I'd like to export my sequence after the shader has been running for 5 seconds, so it can pre-warm the buffers. In this case I'd like to export -sequence,5,10. I've done this, but it just starts from there rather than pre-run from there.

I'd love to be able to have the shader run for -x seconds before it outputs the sequence if possible?

**Comment by patriciogonzalezvivo** [comment]
Hi @willstall, I'm so glad you love glslViewer and becoming a power user : )
Buffers are a lot of fun. That issue you are having is because they are force to go in an order. I found a simple solution by adding a wait command. https://github.com/patriciogonzalezvivo/glslViewer/commit/4c375f159f838ba6274c598229b05f24a82d41e5  

Works like this:
```
wait,<sec>
```
It just hold the command thread <N> amount of secs.
So if you want to call it as an argument you will use it like this:
```bash
glslViewer loop.frag -e wait,5 -E sequence,5,10 
```
This line will wait for 5 seconds before recording a sequence of PNGs between the second 5 to the second 10.

The reason I'm not using `sequence` by it self it's because it hijacks the elapsed time for a specific amount of time. With it you "change" time. So you can have several `sequence` commands that go back and forth to specific moments of your time line.

Please check it out and let me know how it goes

**Comment by willstall** [comment]
Alrighty! I was able to sit down for a bit and do a full make install test etc.

I gave it a shot, but still not really working as I guess I'm expecting. I uploaded a video with all the files so you can see what I'm looking at: [Example Files](https://www.dropbox.com/sh/xjx23esgbwxjcyj/AADdqlyQ6Fi_8ifTyKGxgmbla?dl=0
)

In the record.sh I've done both starting at sequence 5,10 and also played with 0,5 with a -e wait,5

In the video, you can see how my little shader is just oversampling at a point before it's recording the frames

**Comment by patriciogonzalezvivo** [comment]
Hi @willstall, I replay to you by twitter DM. I check what you send. The waiting command holds the commands queue X amount of seconds and then you can add another one. But seams the problem you are experiencing is not related to a "waiting" issue. In your shader you are working with two an unclean buffers.

I clean some of the redundancies on your passes and add a `step(0.5, u_time)` when you are using the previous buffer so it gets "clean" (multiply by zero) at the beginning.

```
#ifdef GL_ES
precision mediump float;
#endif

#define PI 3.14159265359
#define HALF_PI 1.57079632675
#define TWO_PI 6.283185307

#define SECONDS 5.0

uniform sampler2D u_buffer0;
uniform sampler2D u_buffer1;

uniform vec2 u_resolution;
uniform vec2 u_mouse;
uniform float u_time;

vec2 random2(vec2 st) {
    st = vec2( dot(st,vec2(127.1,311.7)),
              dot(st,vec2(269.5,183.3)) );
    return -1.0 + 2.0*fract(sin(st)*43758.5453123);
}

float random(vec2 st) {
    return fract(sin(dot(st.yx,vec2(14.7891,43.123)))*312991.41235);
}

float random (in float x) {
    return fract(sin(x)*43758.5453123);
}

float stepUpDown(float begin, float end, float t) {
  return step(begin, t) - step(end, t);
}

mat2 rotate(float angle) {
    return mat2( cos(angle),-sin(angle),sin(angle),cos(angle) );
}

vec2 center(vec2 st) {
    float aspect = u_resolution.x/u_resolution.y;
    st.x = st.x * aspect - aspect * 0.5 + 0.5;
    return st;
}

vec2 centering(vec2 st,float margin) {
    return st * (1.0 + margin) - margin * .5;
}

vec3 time() {
    float period = mod(u_time,SECONDS);
    vec3 t = vec3(fract(u_time/SECONDS),period, 1.0-fract(period));
    return t;       // return fract(length),period,period phase
}

float scene(vec2 st, vec3 t) {
    st = st * 2.0 - 1.0;

    vec2 pos = vec2(0.0);
    pos += vec2(0.1) * rotate(TWO_PI*t.x*3.0);

    float d = 1.0;
    d = length(st-pos)-.1;

    return d;
}


void main() {
    vec3 color = vec3(0.0);
    vec3 t = time();
    vec2 st = gl_FragCoord.xy / u_resolution.xy;
    float aa = 1.0/u_resolution.x*2.0;

#ifdef BUFFER_0
    // previuos scene
    vec3 prev = texture2D(u_buffer1, st).rgb * 0.99; // Disolve the prev scene by 0.99
    color += prev * step(0.5, u_time);  // Here is the trick clean the prev buffer before second 0.5 

    // current scene
    float s = scene(st, t);
    float current = 1.0 - smoothstep(0.0, aa, s);
    color += vec3(1.0) * current;

#elif defined(BUFFER_1)
    color = texture2D(u_buffer0, st).rgb;
#else
    color = texture2D(u_buffer0, st).rgb;
#endif

    gl_FragColor = vec4(color, 1.0);
}
```
