### ISSUE TITLE
Postprocessing: Texture color changed

### ISSUE THREAD

**Issue by eyworldwide** [patriciogonzalezvivo/glslViewer#139]
When I tried to use  POSTPROCESSING, something strange happened. I didn't change the color in postprocessing pass but the texture's original color is replaced by anothor color.

The rendering result(color changed):
![image](https://user-images.githubusercontent.com/1296667/62459027-f2f85980-b7b0-11e9-89d4-37acb72be27d.png)
The texture(download from https://www.textures.com/download/various0352/69381 ):
![image](https://user-images.githubusercontent.com/1296667/62459079-16bb9f80-b7b1-11e9-8823-ebc83504ed14.png)

It's much more strange that some texture is OK, like this one from the project's example:
![image](https://user-images.githubusercontent.com/1296667/62459318-ab260200-b7b1-11e9-85a4-8623ae093899.png)

![image](https://user-images.githubusercontent.com/1296667/62459445-f2ac8e00-b7b1-11e9-8a8a-04d6b116914a.png)

The command is  `glslViewer teapot.ply test.vert test.frag texture.png`

test.vert:
```glsl
#ifdef GL_ES
precision mediump float;
#endif
uniform mat4 u_modelViewProjectionMatrix;
uniform vec3 u_camera;
uniform vec3 u_light;
uniform vec3 u_lightColor;
uniform vec2 u_resolution;

attribute vec4 a_position;
attribute vec2 a_texcoord;
varying vec4 v_position;
attribute vec4 a_color;
varying vec4 v_color;
attribute vec3 a_normal;
varying vec3 v_normal;
varying vec2 v_texcoord;

void main(void) {
    v_position = a_position;
    v_color = a_color;
    v_normal = a_normal;
    v_texcoord = 0.5 * (vec2(1.0) - u_resolution + v_position.xy);
    gl_Position = u_modelViewProjectionMatrix * v_position;
}
```

test.frag:
```glsl
#ifdef GL_ES
precision mediump float;
#endif

uniform mat4 u_modelViewProjectionMatrix;
uniform vec3 u_camera;
uniform vec3 u_light;
uniform vec3 u_lightColor;
uniform sampler2D u_tex0;
uniform vec2 u_tex0Resolution;
uniform sampler2D u_scene;
uniform sampler2D u_scene_depth;
uniform vec2 u_resolution;

varying vec4 v_position;

varying vec3 v_normal;
varying vec2 v_texcoord;
varying vec4 v_color;

void main(void) {
    vec3 color = vec3(1.0);
    vec2 st = gl_FragCoord.xy/u_resolution.xy;

    #if defined(POSTPROCESSING)
        color = texture2D(u_scene, st).rbg;
    #else
        color = texture2D(u_tex0, v_texcoord).rgb;
        float shade = dot(v_normal, normalize(u_light));
        color *= smoothstep(-1.0, 1.0, shade);
    #endif

    gl_FragColor = vec4(color, 1.0);
}
```
teapot.ply:
[teapot.ply.zip](https://github.com/patriciogonzalezvivo/glslViewer/files/3467208/teapot.ply.zip)

**Comment by patriciogonzalezvivo** [comment]
Hi! in fact you are changing the color : ) take a look to:

```
#if defined(POSTPROCESSING)
    color = texture2D(u_scene, st).rbg;
#else
```

You are doing `.rbg` instead of `.rgb` 

: )

**Comment by eyworldwide** [comment]
Thank you for looking into the code. This is a ridiculous mistake I have made ：）Maybe I should not code in midnight.
