### ISSUE TITLE
Having trouble compiling on Ubuntu 18

### ISSUE THREAD

**Issue by Dragon987** [patriciogonzalezvivo/glslViewer#140]
Hi, I am having trouble building version 1.5.5 on Ubuntu 18.04. I have installed everything from guide and i also compiled glfw3 from source.
Here is my error message:
src/gl/fbo.cpp: In destructor ‘virtual Fbo::~Fbo()’:
src/gl/fbo.cpp:36:9: error: ‘glDeleteRenderbuffers’ was not declared in this scope
         glDeleteRenderbuffers(1, &m_depth_buffer);
         ^~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:36:9: note: suggested alternative: ‘glDeleteRenderbuffersEXT’
         glDeleteRenderbuffers(1, &m_depth_buffer);
         ^~~~~~~~~~~~~~~~~~~~~
         glDeleteRenderbuffersEXT
src/gl/fbo.cpp:37:9: error: ‘glDeleteFramebuffers’ was not declared in this scope
         glDeleteFramebuffers(1, &m_id);
         ^~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:37:9: note: suggested alternative: ‘glDeleteFramebuffersEXT’
         glDeleteFramebuffers(1, &m_id);
         ^~~~~~~~~~~~~~~~~~~~
         glDeleteFramebuffersEXT
src/gl/fbo.cpp: In member function ‘virtual void Fbo::allocate(uint, uint, bool, bool)’:
src/gl/fbo.cpp:47:9: error: ‘glGenFramebuffers’ was not declared in this scope
         glGenFramebuffers(1, &m_id);
         ^~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:47:9: note: suggested alternative: ‘glGenFramebuffersEXT’
         glGenFramebuffers(1, &m_id);
         ^~~~~~~~~~~~~~~~~
         glGenFramebuffersEXT
src/gl/fbo.cpp:54:13: error: ‘glGenRenderbuffers’ was not declared in this scope
             glGenRenderbuffers(1, &m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:54:13: note: suggested alternative: ‘glGenRenderbuffersEXT’
             glGenRenderbuffers(1, &m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~
             glGenRenderbuffersEXT
src/gl/fbo.cpp:72:32: error: ‘GL_FRAMEBUFFER’ was not declared in this scope
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
                                ^~~~~~~~~~~~~~
src/gl/fbo.cpp:72:32: note: suggested alternative: ‘GL_DRAW_BUFFER’
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
                                ^~~~~~~~~~~~~~
                                GL_DRAW_BUFFER
src/gl/fbo.cpp:72:48: error: ‘GL_COLOR_ATTACHMENT0’ was not declared in this scope
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
                                                ^~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:72:48: note: suggested alternative: ‘GL_COLOR_ATTACHMENT0_EXT’
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
                                                ^~~~~~~~~~~~~~~~~~~~
                                                GL_COLOR_ATTACHMENT0_EXT
src/gl/fbo.cpp:72:9: error: ‘glFramebufferTexture2D’ was not declared in this scope
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
         ^~~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:72:9: note: suggested alternative: ‘glFramebufferTextureEXT’
         glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, m_texture, 0);
         ^~~~~~~~~~~~~~~~~~~~~~
         glFramebufferTextureEXT
src/gl/fbo.cpp:76:32: error: ‘GL_RENDERBUFFER’ was not declared in this scope
             glBindRenderbuffer(GL_RENDERBUFFER, m_depth_buffer);
                                ^~~~~~~~~~~~~~~
src/gl/fbo.cpp:76:32: note: suggested alternative: ‘GL_READ_BUFFER’
             glBindRenderbuffer(GL_RENDERBUFFER, m_depth_buffer);
                                ^~~~~~~~~~~~~~~
                                GL_READ_BUFFER
src/gl/fbo.cpp:76:13: error: ‘glBindRenderbuffer’ was not declared in this scope
             glBindRenderbuffer(GL_RENDERBUFFER, m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:76:13: note: suggested alternative: ‘glBindRenderbufferEXT’
             glBindRenderbuffer(GL_RENDERBUFFER, m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~
             glBindRenderbufferEXT
src/gl/fbo.cpp:81:13: error: ‘glRenderbufferStorage’ was not declared in this scope
             glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, m_width, m_height);
             ^~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:81:13: note: suggested alternative: ‘glRenderbufferStorageEXT’
             glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, m_width, m_height);
             ^~~~~~~~~~~~~~~~~~~~~
             glRenderbufferStorageEXT
src/gl/fbo.cpp:83:55: error: ‘GL_DEPTH_ATTACHMENT’ was not declared in this scope
             glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, m_depth_buffer);
                                                       ^~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:83:55: note: suggested alternative: ‘GL_DEPTH_ATTACHMENT_EXT’
             glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, m_depth_buffer);
                                                       ^~~~~~~~~~~~~~~~~~~
                                                       GL_DEPTH_ATTACHMENT_EXT
src/gl/fbo.cpp:83:13: error: ‘glFramebufferRenderbuffer’ was not declared in this scope
             glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:83:13: note: suggested alternative: ‘glFramebufferRenderbufferEXT’
             glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, m_depth_buffer);
             ^~~~~~~~~~~~~~~~~~~~~~~~~
             glFramebufferRenderbufferEXT
src/gl/fbo.cpp:106:13: error: ‘glCheckFramebufferStatus’ was not declared in this scope
         if (glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
             ^~~~~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:106:13: note: suggested alternative: ‘glCheckFramebufferStatusEXT’
         if (glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
             ^~~~~~~~~~~~~~~~~~~~~~~~
             glCheckFramebufferStatusEXT
src/gl/fbo.cpp:106:57: error: ‘GL_FRAMEBUFFER_COMPLETE’ was not declared in this scope
         if (glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:106:57: note: suggested alternative: ‘GL_FRAMEBUFFER_COMPLETE_EXT’
         if (glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
                                                         ^~~~~~~~~~~~~~~~~~~~~~~
                                                         GL_FRAMEBUFFER_COMPLETE_EXT
src/gl/fbo.cpp:113:32: error: ‘GL_RENDERBUFFER’ was not declared in this scope
             glBindRenderbuffer(GL_RENDERBUFFER, 0);
                                ^~~~~~~~~~~~~~~
src/gl/fbo.cpp:113:32: note: suggested alternative: ‘GL_READ_BUFFER’
             glBindRenderbuffer(GL_RENDERBUFFER, 0);
                                ^~~~~~~~~~~~~~~
                                GL_READ_BUFFER
src/gl/fbo.cpp:113:13: error: ‘glBindRenderbuffer’ was not declared in this scope
             glBindRenderbuffer(GL_RENDERBUFFER, 0);
             ^~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:113:13: note: suggested alternative: ‘glBindRenderbufferEXT’
             glBindRenderbuffer(GL_RENDERBUFFER, 0);
             ^~~~~~~~~~~~~~~~~~
             glBindRenderbufferEXT
src/gl/fbo.cpp: In member function ‘virtual void Fbo::bind()’:
src/gl/fbo.cpp:120:23: error: ‘GL_FRAMEBUFFER_BINDING’ was not declared in this scope
         glGetIntegerv(GL_FRAMEBUFFER_BINDING, (GLint *)&m_old_fbo_id);
                       ^~~~~~~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:120:23: note: suggested alternative: ‘GL_ARRAY_BUFFER_BINDING’
         glGetIntegerv(GL_FRAMEBUFFER_BINDING, (GLint *)&m_old_fbo_id);
                       ^~~~~~~~~~~~~~~~~~~~~~
                       GL_ARRAY_BUFFER_BINDING
src/gl/fbo.cpp:124:27: error: ‘GL_FRAMEBUFFER’ was not declared in this scope
         glBindFramebuffer(GL_FRAMEBUFFER, m_id);
                           ^~~~~~~~~~~~~~
src/gl/fbo.cpp:124:27: note: suggested alternative: ‘GL_DRAW_BUFFER’
         glBindFramebuffer(GL_FRAMEBUFFER, m_id);
                           ^~~~~~~~~~~~~~
                           GL_DRAW_BUFFER
src/gl/fbo.cpp:124:9: error: ‘glBindFramebuffer’ was not declared in this scope
         glBindFramebuffer(GL_FRAMEBUFFER, m_id);
         ^~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:124:9: note: suggested alternative: ‘glBindFramebufferEXT’
         glBindFramebuffer(GL_FRAMEBUFFER, m_id);
         ^~~~~~~~~~~~~~~~~
         glBindFramebufferEXT
src/gl/fbo.cpp: In member function ‘virtual void Fbo::unbind()’:
src/gl/fbo.cpp:138:27: error: ‘GL_FRAMEBUFFER’ was not declared in this scope
         glBindFramebuffer(GL_FRAMEBUFFER, m_old_fbo_id);
                           ^~~~~~~~~~~~~~
src/gl/fbo.cpp:138:27: note: suggested alternative: ‘GL_DRAW_BUFFER’
         glBindFramebuffer(GL_FRAMEBUFFER, m_old_fbo_id);
                           ^~~~~~~~~~~~~~
                           GL_DRAW_BUFFER
src/gl/fbo.cpp:138:9: error: ‘glBindFramebuffer’ was not declared in this scope
         glBindFramebuffer(GL_FRAMEBUFFER, m_old_fbo_id);
         ^~~~~~~~~~~~~~~~~
src/gl/fbo.cpp:138:9: note: suggested alternative: ‘glBindFramebufferEXT’
         glBindFramebuffer(GL_FRAMEBUFFER, m_old_fbo_id);
         ^~~~~~~~~~~~~~~~~
         glBindFramebufferEXT
Makefile:60: recipe for target 'src/gl/fbo.o' failed
make: *** [src/gl/fbo.o] Error 1

Thanks in advance.

**Comment by patriciogonzalezvivo** [comment]
hi! seams you don't have OpenGL installed. How did you install GLFW?

**Comment by Dragon987** [comment]
I installed it with cmake and many of my projects use OpenGL with GLFW and GLEW.

**Comment by Dragon987** [comment]
Hi! Just compiled code by adding #include <GL/glew.h> and flags -lGL and -lGLEW but now when I run program i get segfaults.

**Comment by patriciogonzalezvivo** [comment]
a. Could you send the return value for: `pkg-config --libs glfw3 glu gl`. 
b. Sorry to insist. Did you follow this follwoing step describe on the README??

```
** Important Note ** : Glfw3 library in Ubuntu 18.04 is causing troubles. For that you need to compile glfw3 from source (next paragraph)

These instructions may not work for all users. For example, it seems that libglfw3-dev conflicts with the older libglfw-dev. The previous Ubuntu install instructions direct you to download and compile glfw3 manually:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git-core cmake xorg-dev libglu1-mesa-dev
cd ~
git clone https://github.com/glfw/glfw.git
cd glfw
cmake .
make
sudo make install
```

**Comment by Dragon987** [comment]
I reinstalled GLFW and downloaded glslViewer again but the broblem persists. I also checked g++ version and it is 7.4.0. The problem is glBindFramebuffer, glGenerateMipmap , GL_FRAMEBUFFER, glBindRenderbuffer, GL_RENDERBUFFER are not declared.
pkg-config --libs glfw3 glu gl returns -L/usr/local/lib -lglfw -lGLU -lGL

**Comment by Dragon987** [comment]
head /usr/local/include/GLFW/glfw3.h returns following: 
/*************************************************************************
 * GLFW 3.4 - www.glfw.org
 * A library for OpenGL, window and input
 *------------------------------------------------------------------------
 * Copyright (c) 2002-2006 Marcus Geelnard
 * Copyright (c) 2006-2019 Camilla Löwy <elmindreda@glfw.org>
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.

**Comment by patriciogonzalezvivo** [comment]
Interesting in my Ubuntu 18.04 `head /usr/local/include/GLFW/glfw3.h` returns:
           
```          
/*************************************************************************
 * GLFW 3.3 - www.glfw.org
 * A library for OpenGL, window and input
 *------------------------------------------------------------------------
 * Copyright (c) 2002-2006 Marcus Geelnard
 * Copyright (c) 2006-2016 Camilla Löwy <elmindreda@glfw.org>
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
```

Wonder what happen if you downgrade to 3.3? and how you got one version a head

**Comment by Dragon987** [comment]
Thank you very much on support and kindness.
I downgraded to glfw 3.3 and now everything works but i still have no idea how i got glfw 3.4.
Maybe because I cloned glfw repo the first time, but now I just downloaded official release.
PS The glslViewer is really good software and I like it a lot.
Thank you again on support.
