### ISSUE TITLE
Can't open shaders on Raspberry Pi 4

### ISSUE THREAD

**Issue by jmwohl** [patriciogonzalezvivo/glslViewer#141]
`glslViewer` installs via apt-get without issue, but attempting to run a shader with `glslViewer` from the command line results in:

```
* failed to add service - already in use?
```

Any ideas?

**Comment by jmwohl** [comment]
Update: installing `glslViewer` from source is an improvement — it works when running within the desktop environment, opening a small window running the shader. However when I try to run a shader directly from the terminal, outside of the desktop environment, it fails because it can't find the display:

```
GLFW error 0x10008: X11: The DISPLAY environment variable is missing
ABORT: GLFW init failed
```

I tried setting the `DISPLAY` env var to match its value when in the desktop env:

```
export DISPLAY=:0.0
```

But still it fails:

```
GLFW error 0x10008: X11: Failed to open display :0.0
ABORT: GLFW init failed
```

**Comment by patriciogonzalezvivo** [comment]
I just order a RPi4. If the driver of the RPi4  don’t support it there is nothing to do. Is not a GlslViewer issue but more of a hardware driver. I’m curious to get one and see if they have a solution to keep things consistent with the previous Broadcom chips

**Comment by willstall** [comment]
Just checking in here to see if there was any luck =)

**Comment by patriciogonzalezvivo** [comment]
Yeah, I was just trying this with no luck. The GPU chip is different and `libbrcmGLESv2` is deprecated : (

https://github.com/raspberrypi/firmware/issues/1171
https://techyian.github.io/2019-07-03-raspberry-pi-4-opengles-11/

This will need a some deep work.  The solution will imply transitioning to this https://github.com/eyelash/tutorials/blob/master/drm-gbm.c

That said, installing GLFW and compiling it for X11 windows manager works

**Comment by patriciogonzalezvivo** [comment]
Morning! I start doing some work on this. I apologize for all the commits, my workflow back&forth the RPI is terrible. But now seams to be compiling correctly on both RPI < 4 and RPI 4
I need to implement an entire OpenGL ES content generation for RPI4 .

What use to be like this: https://github.com/patriciogonzalezvivo/glslViewer/blob/aa8ecee695687a71c3a3773def12354236511037/src/window.cpp

Now loos like this: https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/window.cpp

The defines flags are way more complicated but seams to work.
Most of the new commands comes from https://github.com/matusnovak/rpi-opengl-without-x

**Comment by patriciogonzalezvivo** [comment]
I'll be doing more testing later next week.

**Comment by patriciogonzalezvivo** [comment]
I have great news! glslViewer is working nativelly on Raspberry Pi 4. VC libraries don't work on new Raspberry Pi, so I add compatibility to DGM ( https://github.com/patriciogonzalezvivo/glslViewer/blob/master/Makefile#L45 ). Also If you want to force GLFW compilation (so they run inside a proper windows in X11) you can compile it with:

```
make DRIVER=glfw
```

I also add a `-f' and '--fullscreen` argument to glslViewer so if you decide to use GLWF you can lunch it at fullscreen for installations.

Note: DGM don't do transparent backgrounds, so once you run glslViewer you will not see the console any more.

![IMG_8351](https://user-images.githubusercontent.com/346914/65823278-10bdca00-e208-11e9-8e54-b74557b1b8e7.jpg)
![IMG_8348](https://user-images.githubusercontent.com/346914/65823282-11eef700-e208-11e9-92c3-4d5cd030af4a.jpg)

**Comment by jmwohl** [comment]
Well that's the best news I've heard all day! :D Thanks so much for working on this @patriciogonzalezvivo!

**Comment by patriciogonzalezvivo** [comment]
My pleasure my friend! Anything to keep being part of https://openframe.io/

**Comment by jvolker** [comment]
Amazing, thanks a lot @patriciogonzalezvivo!

**Comment by boolshark** [comment]
New to Openframe here. I read this thread then bought an RPi4 assuming (oops) it would accept images and shaders because I too desire 4k.  

But after installing from https://openframe.io/install.sh and successfully starting the frame, I've tried many of my own, and public, images, shaders, websites and videos, and it only accepted [this Lego video](https://openframe.io/artwork/5d87e408a38167076035bdae). 

Images always throw:
`* failed to add service - already in use?`

Shaders throw:
```
glsViewer /tmp/shader.frag
* failed to add service - already in use?
```
And videos usually throw "have a nice day ;)""

Will Patricio's solution be merged with the build at https://openframe.io/install.sh or am I just missing something?
