### ISSUE TITLE
Options -x and -y don't do anything on macOS

### ISSUE THREAD

**Issue by Tenchi2xh** [patriciogonzalezvivo/glslViewer#145]
macOS version: 10.14
glslViewer version: 1.5.5

With any values used, the `-x` and `-y` options aren't respected and the window is always centered

**Comment by patriciogonzalezvivo** [comment]
True, as far as I know GLFW don't support that.

**Comment by patriciogonzalezvivo** [comment]
I was wrong. I fix it. now you can set x & y positions. 
https://github.com/patriciogonzalezvivo/glslViewer/commit/3a36ab59b4ebdd7cd6e5eb6235711ec401f61d4d

FYI I'am also working on a fullscreen flag (`-f/--fullscreen`)
