### ISSUE TITLE
0(49) : warning C7532: global function textureLod requires "#version 130" or later

### ISSUE THREAD

**Issue by geotyper** [patriciogonzalezvivo/glslViewer#155]
This is problem of Viewer or code of shader?
Ubuntu 18 , glslViewer work well with examples, but from differ shader show error linking shader

**Comment by patriciogonzalezvivo** [comment]
The shader, textureLod is not a valid function of GLSL version 120.
Are you porting it from ShaderToy? Do you mind sharing the code?

**Comment by patriciogonzalezvivo** [comment]
hi @geotyper, I will close this one, feel free to open it back again if you need to make more questions
