### ISSUE TITLE
Compilation error on Fedora 31 

### ISSUE THREAD

**Issue by Zaya6** [patriciogonzalezvivo/glslViewer#156]
Hi there, I'm having trouble compiling on fedora. I've made sure to follow the directions and install the dependencies. Here's the error message I'm getting. Not sure what's going on since C++ isn't my strongest language.

https://pastebin.com/H7WCEZkj

**Comment by patriciogonzalezvivo** [comment]
Hi! What version of Glfw you have?

**Comment by patriciogonzalezvivo** [comment]
Hi! Seams there were some dependencies to add to compile on Fedora. Please take a look to this https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling#b-compiling-on-fedora-distributions-with-glfw 
Let us know if that works for you
