### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sundylink** [patriciogonzalezvivo/glslViewer#158]
![image](https://user-images.githubusercontent.com/35475866/70767622-fc1bb780-1d9c-11ea-8090-a03f2adac22e.png)

Darwin platform with glfw drivers
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
src/main.o
/usr/bin/clang++ -Wall -O3 -std=c++11 -fpermissive -arch x86_64 -DPLATFORM_OSX -DDRIVER_GLFW -stdlib=libc++  -Isrc/ -Iinclude/ -I/System/Library/Frameworks/GLUI.framework -g -c src/main.cpp -o src/main.o -Wno-deprecated-declarations
In file included from src/main.cpp:14:
src/gl/gl.h:26:10: fatal error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [src/main.o] Error 1
how to fixed?

**Comment by patriciogonzalezvivo** [comment]
Have you follow the compilation steps on the wiki? https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-GlslViewer#e-compiling-on-macos
Seams you don't have GLW3 installed.

For that you can use brew (like the wiki explains) or install it directly from source

**Comment by patriciogonzalezvivo** [comment]
Hi @sundylink, did that worked? I'm going to close this issue, feel free to open it if it not
