### ISSUE TITLE
Significant performance degradation after some hours of running glslViewer instance

### ISSUE THREAD

**Issue by morisil** [patriciogonzalezvivo/glslViewer#159]
I started using glslViewer for the purpose of installations utilizing CRT output, when connected to Raspberry Pi. I can see that my relatively simple shaders are getting slower over time, approximately after 1 day, and no longer run real time. It seems that the effect intensifies. Applies to both, Pi 1 and Pi 3. As a workaround I ask the technicians to restart it every day before the show, but most likely I will introduce automatic restart script.

**Comment by patriciogonzalezvivo** [comment]
Morning! I'm sorry to hear this. Do you know what version of glslViewer is running (run: glslViewer -v)? Did you build it from master or install it throught Raspbian repository? Did you compile it for console or X11 through glwf?  Do you mind sending me the assets to my private email so I can do test. Performance is a very serious and close to my hear issue?

**Comment by morisil** [comment]
I compiled it from master some time ago, because I needed multi buffer support for feedback loops. But the slow down is noticeable also with shaders which does not use extra buffers. Version `1.6.0` or just before releasing it. I will send you the shader which is slowing down (actually all of them are).

**Comment by patriciogonzalezvivo** [comment]
Hi! Sorry for the late reply, do you mind recompiling from source? and seeing if the problem persist?

**Comment by morisil** [comment]
I will try to do it soon.

**Comment by patriciogonzalezvivo** [comment]
I have been using RPi zero, 3 and 4 for uninterrupted lapses of a day and haven't been able to replicate this. I'm going to close it for now. But I'm super open to this kind of perf issues. Performance on RPI is a high priority of the project
