### ISSUE TITLE
glslViewer problem on Visual Studio Code

### ISSUE THREAD

**Issue by RodkarmA** [patriciogonzalezvivo/glslViewer#160]
Hi, i'm trying to set up glslViewer, i did every passage on the terminal (i have the last MacOS) but the visual code terminal is showing me this while the glslViewer window doesn't change color even modifying the vec4  (eventually sorry for my english).

  // > MBP-di-XXX:Test XXX$ glslViewer 005_color.frag
Error linking shader: ERROR: Compiled fragment shader was corrupt.

0: NOT FOUND
// >

**Comment by KamikaTze-K2** [comment]
Question: Are you getting this error message only from within visual studio code? Or also from a system terminal?

My best guess is that your shader code has errors and is failing to compile. That would then have nothing to do with glslViewer or vscode :)

Please try the following: create an empty text file and copy the following fragment shader code into it, then save the file as `test.frag`

```glsl
uniform vec2 u_resolution;
void main(void) {
  vec2 uv = (gl_FragCoord.xy/u_resolution.xy) * vec2(u_resolution.x/u_resolution.y, 1);
  vec3 col = vec3(uv.x, uv.y, 0.3);
  gl_FragColor = vec4(col,1.0);
}
```
Then proceed to open a terminal (or from vscode) and run the following command in the same directory where you saved `test.frag`

```shell
glslViewer test.frag
```

![shader-test](https://user-images.githubusercontent.com/61164060/75074660-7040ad00-54fc-11ea-969f-afdc5cfd3534.png)

If you see something like this then your glslViewer is working fine and you may have errors somewhere in the `005_color.frag` file.

If glslViewer fails to display something as simple as `test.frag` then quite likely something fundamental is broken in your current setup.

**Comment by patriciogonzalezvivo** [comment]
Have you tried changing `1` to `1.0` in 
`vec2 uv = (gl_FragCoord.xy/u_resolution.xy) * vec2(u_resolution.x/u_resolution.y, 1)`

GLSL don't have automatic casting and `1` is an integer while `1.0` is a float number

**Comment by patriciogonzalezvivo** [comment]
@RodkarmA can you share the code on the shader? Seams the problem is reading `005_color.frag` could be that the file is not in that folder you are working on... or that have weird binary data or... something else

**Comment by patriciogonzalezvivo** [comment]
Hi @RodkarmA? Are you experiencing the same problem? If you are do you mind re-opening this thread and provide some answers for the question above? thanks!
