### ISSUE TITLE
Need docs on where to put GLFW dependencies in VS2019 project folder

### ISSUE THREAD

**Issue by slackmage** [patriciogonzalezvivo/glslViewer#161]
Trying to properly install the glfw dependency

I had assumed everything, headers and dll's, should go into the glfw folder, but it appears that the solution is expecting the header file to be elsewhere. Could you please tell me where these all go?

Thanks!

**Comment by slackmage** [comment]
Got this building. When you download GLFW it's files are all named glfw, and the project expects them to be name to be glfw3

Here's how:

Download glfw for windows (32bit) from their site

Copy glfw3.dll to the bin folder 

Copy the .h files (glfw.h and glfwnative.h) to the include/glfw/ folder 

Go to project properties (Alt+F7)
Under Debugging, look to the right
There's an Environment field.
Add your relative path there. In this case it's "bin" (no quotes)

Go to the glslViewer project folder and expand it. 
Click on references
Delete the reference to the glfw project
Add a new reference, and select the glfw project
Click on the reference and look at the properties panel.
The full path should reflect the change to glfw3 now.

Right click on the solution and select Load Project Dependencies.

Now Build the solution and it should succeed

**Comment by patriciogonzalezvivo** [comment]
Hi! I'm not a Windows user. I'm really glad you figure it out. Do you mind making a PR on the documentation of how solve this issue for others? Thanks in advance!
