### ISSUE TITLE
Problem with applying .mtl to .obj using default shaders

### ISSUE THREAD

**Issue by slzatz** [patriciogonzalezvivo/glslViewer#166]
When I load a .obj file in the simplest way:  glslViewer head.obj I do not get the expected output.  Using files from the 3D examples with the head.obj, head.mtl and default.png I get the attached result.  I am using the latest commit from this repository.  I have tried this on three different arch linux machines and am getting the same incorrect output on each one of them.  I have also tried with other .obj/.mtl files of my own with the same incorrect output.  glslViewer is reporting no errors and when I look at uniforms and textures from the console interface everything looks correct.  All other aspects of glslViewer work as expected when I use my own shaders and it seems essentially impossible that I am the only one encountering this problem with the default shaders and I am completely stumped so any thoughts/advice would be helpful as would someone compiling the current commit on arch and seeing whether they get the expected output.  I have attached a screenshot.
![screenshot](https://user-images.githubusercontent.com/6781999/76091420-84b88700-5f8b-11ea-8f7c-21a324bb82d0.png)

**Comment by patriciogonzalezvivo** [comment]
Hi @slzatz ! Yes I'm familiar with this problem, I only experienced when I'm not using a proper GPU but the integrated on the Intel processor. What are the specs of your machine? In mine linux distro I need to run it with offload-glx.

Of course that's not a real solution. I have to do some work on the default PBR shader to make it compatible with Intel's GPU as well. 

Thanks for getting in touch. I will report progress back

**Comment by slzatz** [comment]
Thank you for the quick response.  Yes, I am running on a lenovo laptop and intel nuc and they have intel integrated graphics processors.  The one on the laptops is described by glxinfo as
Intel HD Graphics 620 (Kaby Lake GT2).  I spent a fair amount of time trying to debug the problem but could not figure out what code in the PBR shader was driving the incorrect result.  I'll keep playing with it and if you make any progress I'd be happy to test code on my machines.

**Comment by slzatz** [comment]
I am not sure this will be helpful but when I turn on MESA debug, I get the following:

    Mesa: User error: GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)

**Comment by patriciogonzalezvivo** [comment]
Hi! I had some time to look into this and i fix the issue with https://github.com/patriciogonzalezvivo/glslViewer/commit/9b5b80b9b940a9dda686cf13e3a89e383bf0be8d

Do you mind pulling master and try it again?

**Comment by slzatz** [comment]
That fixed it.  So can report that with integrated Intel graphics - in my case Intel HD Graphics 620 the default PBR shader works.  Thanks again for all the great work.

**Comment by patriciogonzalezvivo** [comment]
yay!
