### ISSUE TITLE
Viewer not loading on Raspberry Pi 4

### ISSUE THREAD

**Issue by thatguyjk** [patriciogonzalezvivo/glslViewer#169]
I followed the instructions to compile glslViewer from source but when I go to run one of the examples glslViewer gives me a blank prompt and the viewer never appears. 

[![glsl-terminal-error.png](https://i.postimg.cc/dV0VdFsb/glsl-terminal-error.png)](https://postimg.cc/2VPYRPBG)

**Comment by patriciogonzalezvivo** [comment]
Seams you are in a X11 context. Did you compile for X11 or for the console?
```
make DRIVER=glfw
or
make DRIVER=gbm
```
