### ISSUE TITLE
VS2019 no compile

### ISSUE THREAD

**Issue by angelbpineda** [patriciogonzalezvivo/glslViewer#171]
Hola,
He seguido los pasos de la compilacion para Windows10: https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-GlslViewer#f-compiling-on-windows, pero VS2019 sale error (lo mismo para Win32):

1>------ Operación Compilar iniciada: proyecto: glslViewer, configuración: Release x64 ------
1>LINK : fatal error LNK1104: no se puede abrir el archivo 'C:\Users\a****\Dev\glslViewer\bin\x64\Release\rgbe.lib'
1>Compilación del proyecto "glslViewer.vcxproj" terminada -- ERROR.
========== Compilar: 0 correctos, 1 incorrectos, 5 actualizados, 0 omitidos ==========

**Comment by ThomasChen1220** [comment]
I'm getting this: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'GLFW/glfw3.h': No such file or directory	glslViewer	D:\indie\Shader\glslViewer\src\window.cpp	39	

when I try to compile on VS2019

**Comment by patriciogonzalezvivo** [comment]
make sure the GLFW submodule have been clone as well

**Comment by moebiussurfing** [comment]
hey, I am stuck on the last step, 
```.bash
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "glob.h"	glslViewer	F:\GLSL\glslViewer\src\io\fs.cpp
```
	
I have used the master branch. Should I use the previous tagged release?

![glslviewer](https://user-images.githubusercontent.com/2106149/106994800-3f34a900-675c-11eb-9b35-240e691f5267.PNG)

**Comment by jumar** [comment]
> hey, I am stuck on the last step,
> 
> ```shell
> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)	E1696	cannot open source file "glob.h"	glslViewer	F:\GLSL\glslViewer\src\io\fs.cpp
> ```
> 
> I have used the master branch. Should I use the previous tagged release?
> 
> ![glslviewer](https://user-images.githubusercontent.com/2106149/106994800-3f34a900-675c-11eb-9b35-240e691f5267.PNG)

I had the same issue but switching to the 1.6.8 tag solved it.

**Comment by patriciogonzalezvivo** [comment]
Hi! This error have been introduced recently bringing image sequence support. Seams `glob.h` is posix specific. For the time being use the tag described above 

https://stackoverflow.com/questions/15052998/what-to-substitute-for-glob-t-and-glob-on-port-to-windows

**Comment by patriciogonzalezvivo** [comment]
I open an new issue to keep track of this. I will close this one for the moment.

@ThomasChen1220 did you check if you correctly have clone GLFW?
