### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by GuillaumeSeg** [patriciogonzalezvivo/glslViewer#173]
Hello,
Thanks for developing this wonderful tool !
I'm having trouble with the export feature.
I want to export my fragment shader in a image output,
so i use the command like that 
```
glslViewer mosaics15.frag -w 300 -h 300 -o test.png           
// Will save screenshot to test.png on exit.
// > %                 
``` 
but when I exit the program I can't find the result of the export, I'm with macOS Sierra

**Comment by daniellimws** [comment]
I am also facing this issue on macOS Mojave.

**Comment by patriciogonzalezvivo** [comment]
What version of glslViewer are you running? compiled from code or using brew?

**Comment by GuillaumeSeg** [comment]
GlslViewer 1.6.0 using brew on Mac
and I tried on Windows with the master branch, and same issue

**Comment by patriciogonzalezvivo** [comment]
You are right... I just give it a shot and didn't work. I will look it out. In the mid time try this:

```
glslViewer examples/2D/00_tests/test.frag -w 300 -h 300 -E screenshot,test.png 
``` 

Context:
`-e` executes a command while `-E` executes a command and then exits.
`screenshot,<filename>` is the console command to make a screenshot

**Comment by patriciogonzalezvivo** [comment]
Ok... I think I found it... `-o <filename>` only seams to work when `-s <seconds>` is present. 
This is way to much over convoluted and is a part of old legacy code where simple order could be set as app parameters. I'm going to move forward to the `-e <command>` style which is more flexible. In case of  wanting to reproduce the the equivalente of 

```
glslViewer mosaics15.frag -w 300 -h 300 -o test.png -s 10
```

you could do 


```
glslViewer mosaics15.frag -w 300 -h 300 -e wait,10.0 -E screenshot,test.png
```

This should:
1. execute the first command first: `wait,10` which wait for 10 seconds
2. excecute `screenshot,test.png` which makes a screenshot and save it into `test.png`
3. exit

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/glslViewer/commit/e10c52a7136ccf6d8ec95662f5a251bc21ee210b

**Comment by GuillaumeSeg** [comment]
Thank you very much. I'll try it !
