### ISSUE TITLE
is there a way to enable GL_VERTEX_PROGRAM_POINT_SIZE?

### ISSUE THREAD

**Issue by nowakf** [patriciogonzalezvivo/glslViewer#174]
I wanted to render a point cloud, and from the little looking around I did, calling glEnable(GL_VERTEX_PROGRAM_POINT_SIZE) seemed to be the normal way to do this. Is there a way to do this from within glslviewer?

**Comment by patriciogonzalezvivo** [comment]
In the vertex shader you can do: 

gl_PointSize = <float number>;

**Comment by nowakf** [comment]
Oh OK! I tried that in a fragment shader - which obviously makes no sense. Thanks!
