### ISSUE TITLE
add option to change default header file

### ISSUE THREAD

**Issue by Dsm0** [patriciogonzalezvivo/glslViewer#175]
I'd love the option to specify a file with custom boilerplate to load

**Comment by patriciogonzalezvivo** [comment]
What do you mean? What would be the use cases for it?

**Comment by Dsm0** [comment]
currently, when glslViewer is passed a filepath that doesn't exist yet, it loads `src/shaders/default_scene.h`.

I think it would be nice to have this as a parameter that could be changed.
For instance, if I wanted to instead load a copy of one of the example files, I could just re-define the `default shader` path, and load that example every time a new file was created.

(sorry for the late reply)

**Comment by patriciogonzalezvivo** [comment]
oh! I see. I see how that could make sense specially for default 2D and 3D shader. Let me think on how would be an elegant implementation of that that follows the lines of the CSV commands and app arguments.

Thanks for the suggestion

**Comment by patriciogonzalezvivo** [comment]
hi! I just made this commit https://github.com/patriciogonzalezvivo/glslViewer/commit/2fd9d7b6d8ed2e702b75b04b746337b3657393dc that introduce two types of 2D default shaders. This leave to automatically creating 3 types of default shaders when `.frag` are not found: 
* 2D default shader with the tipical color gradient and u_time animation
* 2D default shader with one or two textures when textures are present
* 3D default shader with PBR shader when geometry are present

Let me know if this is in line with something you where expecting. I will close it for now, but feel free to open back again
