### ISSUE TITLE
Feature request: uniform list in --help

### ISSUE THREAD

**Issue by orazdow** [patriciogonzalezvivo/glslViewer#177]
I think it would be helpful to be able to print the input uniform names. Either in the main help, or in a separate command like --help-uniforms.

Would this be something you would be open to having a pull request submitted for?

**Comment by patriciogonzalezvivo** [comment]
Hi there! There is such command is call `uniforms` here it's an example:

```
[~/Desktop/glslViewer]$ glslViewer examples/3D/03_models/helmet.glb -C examples/3D/01_lighting/uffizi_cross.hdr                                                                               [master] 
// examples/3D/01_lighting/uffizi_cross.hdr loaded as: 
//    uniform samplerCube u_cubeMap;
//    uniform vec3        u_SH[9];
// > uniforms
vec3,u_SH
vec3,u_camera,-0.000,-0.000,3.532
samplerCube,u_cubeMap
float,u_iblLuminance,0.78125
sampler2D,u_lightShadowMap
vec3,u_model,0.002,-0.000,0.187
mat4,u_modelViewProjectionMatrix
vec2,u_resolution,500,500
sampler2D,u_texture0,
sampler2D,u_texture1,
sampler2D,u_texture2,
sampler2D,u_texture3,
sampler2D,u_texture4,
u_light,0.000,176.600,176.600
u_lightColor,1.000,1.000,1.000
u_lightIntensity,1.000
```

On it you can see that by sending the command `uniforms` it will print all the uniform variables that have been send... similarly you have `defines` and `textures`

```
// > defines

mesh_helmet_lp_13930damagedhelmet
-------------- 
#define GLSLVIEWER 160
#define LIGHT_SHADOWMAP u_lightShadowMap
#define LIGHT_SHADOWMAP_SIZE 1024.0
#define MATERIAL_BASECOLOR vec4(1.000,1.000,1.000,1.000)
#define MATERIAL_BASECOLORMAP u_texture0
#define MATERIAL_EMISSIVE vec3(1.000,1.000,1.000)
#define MATERIAL_EMISSIVEMAP u_texture1
#define MATERIAL_METALLIC 1.000000
#define MATERIAL_NAME_MATERIAL_MR 
#define MATERIAL_NORMALMAP u_texture4
#define MATERIAL_OCCLUSIONMAP u_texture3
#define MATERIAL_ROUGHNESS 1.000000
#define MATERIAL_ROUGHNESSMETALLICMAP u_texture2
#define MODEL_NAME_MESH_HELMET_LP_13930DAMAGEDHELMET 
#define MODEL_PRIMITIVE_TRIANGLES 
#define MODEL_VERTEX_NORMAL v_normal
#define MODEL_VERTEX_TANGENT v_tangent
#define MODEL_VERTEX_TEXCOORD v_texcoord
#define PLATFORM_LINUX 
#define SCENE_CUBEMAP u_cubeMap
#define SCENE_SH_ARRAY u_SH
```

```
// > textures
sampler2D,u_texture0,
sampler2D,u_texture1,
sampler2D,u_texture2,
sampler2D,u_texture3,
sampler2D,u_texture4,
```

It's possible to view the textures on the viewport by doing `textures,on`:

![image](https://user-images.githubusercontent.com/346914/84571211-a6719900-ad46-11ea-8ea1-2cfba28f9ebb.png)

In a similar way it's possible to view the different buffers by doing `buffers,on`:

![image](https://user-images.githubusercontent.com/346914/84571232-c86b1b80-ad46-11ea-8373-a848efdb92a6.png)

In the same spirit you can turn on the histogram by doing `histogram,on`

![image](https://user-images.githubusercontent.com/346914/84571251-f2bcd900-ad46-11ea-853f-ad6d65b0dde7.png)

Similarly you can turn all of above plus `axis,on`, `grid,on` and `bboxes,on` by just sending the command `debug,on`. 

![image](https://user-images.githubusercontent.com/346914/84571322-5a732400-ad47-11ea-9113-aad551f049b1.png)

If you want to turn one of them off you just need to type the same `[command],off`

Hope this is useful and thank you for using glslViewer : )

**Comment by orazdow** [comment]
Oh, I didn't realize there was a shell feature while it's running. That's awesome. I was more referring to listing all the possible uniforms that are listed [here](https://github.com/patriciogonzalezvivo/glslViewer/wiki/GlslViewer-UNIFORMS) for easy lookup, since the uniforms command prints only the ones implemented in the shader.

**Comment by patriciogonzalezvivo** [comment]
@orazdow If you do 
```
// > help 
```
You will find that `uniforms,all` print all supported uniforms

```
// > uniforms,all
vec3,u_SH
vec3,u_camera,-0.000,-0.000,2.606
float,u_cameraAperture,16
float,u_cameraDistance,2.6057
float,u_cameraEv100,14.9658
float,u_cameraExposure,2.60417e-05
float,u_cameraFarClip,1000
float,u_cameraNearClip,0.01
float,u_cameraSensitivity,100
float,u_cameraShutterSpeed,0.008
samplerCube,u_cubeMap
vec4,u_date,2020.000,5.000,16.000,23988.016
float,u_delta,0.0163651
float,u_iblLuminance,0.78125
sampler2D,u_lightShadowMap
vec3,u_model,-0.000,-0.000,-0.000
mat4,u_modelMatrix
mat4,u_modelViewProjectionMatrix
vec2,u_mouse,0,0
mat3,u_normalMatrix
mat4,u_projectionMatrix
vec2,u_resolution,500,500
sampler2D,u_scene
sampler2D,u_sceneDepth
float,u_time,4.99067
mat3,u_view2d
mat4,u_viewMatrix
u_light,0.000,130.285,130.285
u_lightColor,1.000,1.000,1.000
u_lightIntensity,1.000
```
