### ISSUE TITLE
Please add command line option to rotate the output

### ISSUE THREAD

**Issue by jvolker** [patriciogonzalezvivo/glslViewer#178]
I'm trying to run GlslViewer on a Raspberry Pi 4 using a rotated screen and Openframe.

Unfortunately, the screen rotation settings set by xrandr have no effect in command line mode (used by Openframe) using the FKMS driver (default for Pi4). Therefore glslViewer output is not rotated like it used to be using the legacy graphics driver (prior to Pi4).
One solution (for Openframe) would be to rotate all applications. From my understanding, all applications not relying on X need to implement their own way of rotating the output. Besides glslViewer there is omxplayer and VLC which both provide ways to rotate the output. GlslViewer is the only one not implementing it yet.
Ideally, there would be a global setting which would be used by all applications but I don't know if that's possible.

More on this here: https://openframe.discourse.group/t/rotate-usb-touch-screen-pi-4-raspbian-buster/94/2

Thanks.

**Comment by patriciogonzalezvivo** [comment]
Hi! This is a rather a particular case that seams to be more related to FKMS than glslViewer.
Doing some googling I [found this](https://github.com/MichMich/MagicMirror/wiki/Configuring-the-Raspberry-Pi) solution for the /boot/config.txt:
```
dtoverlay=vc4-fkms-v3d
```

**Comment by jvolker** [comment]
I agree, the use case is rather particular.

> Doing some googling I found this solution for the /boot/config.txt:
>
> `dtoverlay=vc4-fkms-v3d`

This turns on the fkms driver. Then xrandr is handling the display rotation.

Xrandr doesn't in this case though, as it only affects the x server environment. Everything run in command line mode remains unrotated. More on this [here](https://openframe.discourse.group/t/rotate-usb-touch-screen-pi-4-raspbian-buster/94/3?u=jerry).
