### ISSUE TITLE
Compilation fails on Pi 4 B

### ISSUE THREAD

**Issue by jvolker** [patriciogonzalezvivo/glslViewer#179]
I'm trying to run glslViewer as part of Openframe on a Raspberry Pi 4 B with Raspberry Pi OS (32-bit) with desktop (2020-05-27). The installation fails as part of the Openframe install but also following the [compiling glslViewer](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-GlslViewer#cc-compiling-for-videocore-vi-drivers-raspberry-pi-version-4-and-up) guide.

Running `make` fails: 
```
RPI4 platform with gbm drivers
src/defines.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI4 -DDRIVER_GBM -Wno-psabi -Isrc/ -Iinclude/ -I/usr/include/libdrm -I/usr/include/GLES2 -g -c src/defines.cpp -o src/defines.o -Wno-deprecated-declarations
src/uniforms.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI4 -DDRIVER_GBM -Wno-psabi -Isrc/ -Iinclude/ -I/usr/include/libdrm -I/usr/include/GLES2 -g -c src/uniforms.cpp -o src/uniforms.o -Wno-deprecated-declarations
In file included from src/gl/fbo.h:3,
                 from src/uniforms.h:8,
                 from src/uniforms.cpp:1:
src/gl/gl.h:14:10: fatal error: xf86drm.h: No such file or directory
 #include <xf86drm.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:85: src/uniforms.o] Error 1
```

Thanks.

**Comment by patriciogonzalezvivo** [comment]
Hi! I haven't update to the Raspberry OS yet but I'm a bit confuse. the 32bit version is for desktop and not actually for the Arm RaspberryPi boards. Right?

**Comment by jvolker** [comment]
No, it's for the Pis. I think the term desktop is referring to X server: https://www.raspberrypi.org/downloads/raspberry-pi-os/

The PC "desktop" version of Raspbian is this one: https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

**Comment by jvolker** [comment]
I've tested using `make DRIVER=glfw` (by installing Openframe-GlslViewer) for x11 mode using `raspbian-2020-02-14` and `raspbian-2020-02-05`. 

They throw this error:
```Package glfw3 was not found in the pkg-config search path.```

**Comment by jvolker** [comment]
I've also tried `raspbian-2019-09-26` … same error.

**Comment by jvolker** [comment]
Same error on `raspbian-2019-07-10`.

**Comment by jvolker** [comment]
This is weird. Installing from master used to work for on 20/09/2019. Going back to https://github.com/patriciogonzalezvivo/glslViewer/commit/8a4f4d7f88dd36673c26196983ac7031178d763b and trying to install/compile doesn't work either.

**Comment by patriciogonzalezvivo** [comment]
How did you install GLWF? packages or from source?

**Comment by patriciogonzalezvivo** [comment]
Hi! I have update some important aspects of the code together with the documentation https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling

Please try again, and let me know how it went.

All the best,

Patricio
