### ISSUE TITLE
glfw git clone is borked (Permission denied)

### ISSUE THREAD

**Issue by Tcll** [patriciogonzalezvivo/glslViewer#18]
root@tcll-AY589AAR-ABA-a4317c:~# git clone git@github.com:glfw/glfw.git
    Cloning into 'glfw'...
    Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

why not simply:

    sudo apt-get install glslViewer

**Comment by patriciogonzalezvivo** [comment]
I think you are confuse between glfw and glslViewer

**Comment by Tcll** [comment]
no, I suggested apt-get because it would auto-install everything needed with no issues.

it's better than having to build.

**Comment by Tcll** [comment]
also, please don't close an issue until it is resolved, your installation instructions still provide a broken git clone:

    git clone git@github.com:glfw/glfw.git

**Comment by patriciogonzalezvivo** [comment]
try with https://github.com/glfw/glfw.git

**Comment by patriciogonzalezvivo** [comment]
adding glslViewer to repository manager will not solve the fact that you need to compile glfw libraries

**Comment by Tcll** [comment]
ok, the URL you provided works, however:

    root@tcll-AY589AAR-ABA-a4317c:~# cd glfw
    root@tcll-AY589AAR-ABA-a4317c:~/glfw# make
    make: *** No targets specified and no makefile found.  Stop.

> adding glslViewer to repository manager will not solve the fact that you need to compile glfw libraries

maybe, maybe not... other applications seem to install all requirements automatically.

obtw, +1 for using GLFW over SDL ;)

**Comment by patriciogonzalezvivo** [comment]
Please read and follow the GLFW install tutorial link ( http://www.glfw.org/docs/latest/compile.html#compile_deps_x11 ). You need to have cmake and other things first. Because this is not glslViewer specific I will close this issue

**Comment by Tcll** [comment]
... you're basically asking me to become a developer to install a simple application...

why don't you distribute a pre-built DEB package installer or add the automated build system to the repository, that way you prevent issues such as this.

**Comment by Tcll** [comment]
so I've done what you said and the source still fails to build:

    //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

the full console output is too long to simply copy, so this is just the error.

might I siggest just building x86 binaries (since those run on everything) and distribute a DEB or MSI/EXE.
(I don't believe you really need to worry about x86/x64 when it comes to GLSL)

**Comment by patriciogonzalezvivo** [comment]
GLFW is not installed or compiled correctly (the error is on /usr/local/lib/libglfw3.a) . You should ask this questions in GLFW forum. 

While you are there ask them to make a .deb of GLFW.

Please use the issue page of this repository for questions regarding glslViewer

**Comment by Tcll** [comment]
>While you are there ask them to make a .deb of GLFW.

this is not my project, I've had GLFW installed already, and working, I just didn't have the src headers and apparently glfw library required for glslViewer.

    import pyglfw.pyglfw as GLFW # requires a working glfw library

I'm asking for a .deb of glslViewer

**Comment by Tcll** [comment]
> While you are there ask them to make a .deb of GLFW.

are you asking me to request this for you??
