### ISSUE TITLE
Error 127 when compiling on Fedora 32

### ISSUE THREAD

**Issue by teraspora** [patriciogonzalezvivo/glslViewer#180]
I installed the prerequisites, cloned the repo, then compile attempt failed. 
```
make: execvp: g++: Permission denied
make: *** [Makefile:85: src/defines.o] Error 127
```
Log attached.
[compile_error.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/4782022/compile_error.txt)

**Comment by patriciogonzalezvivo** [comment]
Hi! that's an OS level error, seams `defines.o` was made by another user or with `sudo` permissions. It's possible you have run `sudo make` in the past? 

Try doing 

```
sudo make clean
make
```

**Comment by teraspora** [comment]
Thaat did not solve it, but installing `g++` did.   Perhaps `gcc-g++` could be included in the list of packages to install first?

I got another error but will close this and create a new issue.

**Comment by patriciogonzalezvivo** [comment]
I don't have no much experience with Fedora, if you do and solve the issue do you mind changing the wiki to reflect the needed steps? THANKS!

**Comment by teraspora** [comment]
Sure Patricio, once I have it compiled successfully and working I will be
happy to contribute by editing the wiki. :)

Best regards,
John
