### ISSUE TITLE
How to save a shader?

### ISSUE THREAD

**Issue by annada-behera** [patriciogonzalezvivo/glslViewer#182]
I have written a shader, say `myShader.frag`. I can view the shader by issuing the command

glslViewer myShader.frag

How to save the shader, maybe as a PNG file?

**Comment by factotvm** [comment]
Hi, thank you for the tool. I find myself wondering the same thing. I noticed in e10c52a that you removed the `-o` flag. I also tried using the undocumented `--screenshot` flag from [main.cpp](https://github.com/patriciogonzalezvivo/glslViewer/blob/db3d3afa9e760e886afc507da101fd76822b589a/src/main.cpp#L500), but receive the error: `Error watching for file --screenshot ./02/tmp-hello_world.png`. By the way, I'm attempting to follow along and build [The Book of Shaders](https://thebookofshaders.com) and would like to provide to them a fix to the code that [generates](https://github.com/patriciogonzalezvivo/thebookofshaders/blob/master/src/parseBook.py#L48) the book.

Also, might I suggest changes such as removing a flag should constitute a major version bump (e.g. to `2.0.0`) in the future?

**Comment by patriciogonzalezvivo** [comment]
Hello Daniel, i understand your frustration, sorry for that. From version 1.6 I decide to
migrate for a model that allow adding more functionality which could be call on run time.

For that I favor on using console IN commands. Please take a look to the wiki https://github.com/patriciogonzalezvivo/glslViewer/wiki/Using-GlslViewer#console-in-commands

The command to take a screenshot is:

screenshot,image.png

For keeping old functionality I add to arguments -e [command] and -E [command] . The first one execute the command once the shader is loaded and ready while the second one execute the command and then exits.

So if you want to just take a screenshot of a shader you can do:

glslViewer your.frag -E screenshot,image.png

Let’s say you want to take a screenshot but at second 10 you can do

glslViewer your.frag -e wait,10 -E screenshot,image.png

Hope this helps you. 
All the best 

Patricio

**Comment by patriciogonzalezvivo** [comment]
Hi, i understand your frustration, sorry for that. From version 1.6 I decide to
migrate for a model that allow adding more functionality which could be call on run time.

For that I favor on using console IN commands. Please take a look to the [wiki section on commands](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Using-GlslViewer#console-in-commands)

Once you load the shader the command to take a screenshot is:

```
//> screenshot,image.png
```

For keeping old functionality I add to arguments `-e [command]` and `-E [command]` . The first one execute the command once the shader is loaded and ready while the second one execute the command and then exits.

So if you want to just take a screenshot of a shader you can do:

```
glslViewer your.frag -E screenshot,image.png
```

Let’s say you want to take a screenshot but at second 10 you can do:

```
glslViewer your.frag -e wait,10 -E screenshot,image.png
```

Hope this helps. 
All the best

**Comment by patriciogonzalezvivo** [comment]
I'm going to close this thread unless you have more questions
