### ISSUE TITLE
Couldn't install through PPA (Ubuntu 19:10)

### ISSUE THREAD

**Issue by rossanag** [patriciogonzalezvivo/glslViewer#183]
Hello, this is the error I am getting:
```
Err:18 http://ppa.launchpad.net/patriciogv/glslviewer-ppa/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
```
On a side note I compiling the source code, but it doesn't catch the changes to the code more than once. It takes into account just the first change to the code, any change after it it's ommited. Do I put the binary into a special folder?

Thanks so much

**Comment by patriciogonzalezvivo** [comment]
Hi @rossanag! Thanks for surfacing this up! Originally I wasn't building for Ubuntu 19.10 but just 20.04 and 20.10, but I just extend it for Ubuntu 19.04  and Ubuntu 19.10 https://launchpad.net/~patriciogv/+archive/ubuntu/glslviewer-ppa

Please, do you mind trying again?

Regarding the second Issue? you mean is not hot reloading the shaders on change? Where glslViewer was installed? where the shaders are located? do they have special permissions? If that problem still happening do you mind opening a new issue with it so we can track it and work together to resolve it?

Thanks so much!

**Comment by rossanag** [comment]
> Hi @rossanag! Thanks for surfacing this up! Originally I wasn't building for Ubuntu 19.10 but just 20.04 and 20.10, but I just extend it for Ubuntu 19.04 and Ubuntu 19.10 https://launchpad.net/~patriciogv/+archive/ubuntu/glslviewer-ppa
> 
> Please, do you mind trying again?
Hello Patricio, thanks for your quick response. Now I could install from the PPA repositories without any problem.

> 
> Regarding the second Issue? you mean is not hot reloading the shaders on change? Where glslViewer was installed? where the shaders are located? do they have special permissions? If that problem still happening do you mind opening a new issue with it so we can track it and work together to resolve it?
> 
Regarding the version I compiled I put it under my user folder /home/rossig/glslViewer/ and it had all the permissions.
Now I went back to the Linux installation instructions, everything went well, but I have to save the changes I made to the .frag file to reflect the changes in the code. I am running glslViewer at the VSCode terminal.

I could try to update my Ubuntu version...nonetheless, thanks for made this incredible tool available for other versions.
Thanks!

Ro


> Thanks so much!

**Comment by patriciogonzalezvivo** [comment]
yes, exactly you need to save the file. GlslViewer have no other way to know the changes happened with out saving. I'm happy all went well. I'm going to close the issue. If you have troubles installing from the PPA let me know. Is our new feature and I'm excited people taking advantage of the latest updates

**Comment by patriciogonzalezvivo** [comment]
I'm going to close this thread. feel free to open it back if you have no more questions
