### ISSUE TITLE
Alpha-Channel for Snapshots and Viewer

### ISSUE THREAD

**Issue by gregor-i** [patriciogonzalezvivo/glslViewer#190]
Hi Guys,

I'm not sure if this is a bug report or a feature request. I want to save a snapshot of an fragment shader, which uses transparent parts. But the saved image is black instead of transparent. The Viewer seems to have the same issue.

Here is a minimal example:
```sh
glslViewer alpha-shader.frag \
  -E screenshot,alpha.png \
  -w 128 \
  -h 128 \
  --headless
```

`alpha-shader.frag`:
```glsl
void main(){
    gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);
}
```

Which will save in the following image:
![alpha](https://user-images.githubusercontent.com/18046543/96501893-52754480-1251-11eb-831c-18846a27f3ff.png)

I'm using version `1.6.8` on ubuntu.

Maybe I'm just missing the right option? Otherwise I'd like to provide a pull request.

**Comment by patriciogonzalezvivo** [comment]
Mmm... I will take a look to it.
Personal note: maybe I got the wrong order here https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/sandbox.cpp#L482-L494

**Comment by gregor-i** [comment]
I've played around with that code fragment and I think I found the problem. It seems to be with the blending.

Simply turning of blending (removing `glEnable(GL_BLEND)`) solved the issue.
Also changing the blend function from `GL_ONE_MINUS_SRC_ALPHA` to `GL_ONE_MINUS_DST_ALPHA` solved the issue. 

I don't have enough knowledge about opengl to give any advice; I'm just trying out some things.

**Comment by patriciogonzalezvivo** [comment]
Ok... changed! I notice the glEnable should be there.
Let me know if this works for you. Thanks for pointing this out, is an expected behavior so was to capture it
https://github.com/patriciogonzalezvivo/glslViewer/commit/41c87d7abe1b18660180c979967e3edd9d0c088c
