### ISSUE TITLE
Replace glob.h on Windows

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/glslViewer#197]
hey, I am stuck on the last step, 
```.bash
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "glob.h"	glslViewer	F:\GLSL\glslViewer\src\io\fs.cpp
```
	
I have used the master branch. Should I use the previous tagged release?

![glslviewer](https://user-images.githubusercontent.com/2106149/106994800-3f34a900-675c-11eb-9b35-240e691f5267.PNG)

__Originally posted by @moebiussurfing in https://github.com/patriciogonzalezvivo/glslViewer/issues/171#issuecomment-773806274__

**Comment by nitinp007** [comment]
I am hitting the same issue.  What is the fix for windows? I clone the master today.

**Comment by patriciogonzalezvivo** [comment]
It should be fixed in a way that can compile, after this commit https://github.com/patriciogonzalezvivo/glslViewer/commit/019e6ade1c795b5cab88083b60bf6be8df83c2fc

But I'm not sure that it works correctly
