### ISSUE TITLE
GLFW window not animating raspi 3b+

### ISSUE THREAD

**Issue by BjarneJensen** [patriciogonzalezvivo/glslViewer#198]
Hi, I have tried to build with different driver settings (DRIVER=fakekms, gbm, glfw, kms, legacy). They all compile but so far only legacy and glfw work. I am trying to get glslViewer running on raspi3b+ headless, It works in legacy mode, but when I open it in GLFW mode (using startx), the image comes up, but it does not animate or update when the file is changed. **Any idea why it wont animate?** I would like to run it headless alongside some ofx and processing sketches, so I thought glfw would be best, but I'm not really sure about different diver modes and the benefits they offer in this context. **What are the optimal settings for headless Pi 3b+ with live updates?**

 I was a bit unsure of the documentation for pi3 vs 4 but I may have missed something. I could also be launching them the wrong way.

Thanks for your contributions to the community!

**Comment by patriciogonzalezvivo** [comment]
Hi! Legacy is for older than Raspberry Pi 4 and Fake_Kms is for raspberry pi 4. Both modes are for running WITHOUT x11 (a window manager) that means directly from the console, no startx. If you want to run it inside a window manager GLFW is your option. About the animation. Do you mind sharing the code? 
 
You can run GlslViewer with the argument ‘—headless’ that means you will see nothing, the program will run with no visible context.

**Comment by BjarneJensen** [comment]
Thanks so much for the info and quick response. It is a simple rotating polygon. My apologies for not being clear about my setup. I would like to connect to the headless PI 3 via ssh and run glslviewer on an external monitor. I found it works if I do `startx `wait for it to start, `export DISPLAY=:0`, then `glslViewer test.frag`, while If I run `startx glslViewer test.frag` It does not update. Is there a better way to launch GLFW via ssh? Thanks
```

` 
#test.frag
#ifdef GL_ES
precision mediump float;
#endif

const float PI=3.14159265359;

uniform vec2 u_resolution;
uniform float u_time;
float polygon(vec2 position, float radius, float sides){
  position=position*2.0-1.0;
  float angle=atan(position.x,position.y);
  float slice=PI*2.0/sides;
  return step(radius,cos(floor(.5+angle/slice)*slice-angle)*length(position));

}
mat2 rotate(float angle){
  return mat2(cos(angle),-sin(angle),sin(angle),cos(angle));
}
void main(){
vec2 coord=gl_FragCoord.xy/u_resolution;
vec3 color=vec3(0);
//float poly=polygon(coord,.3,3.0);

coord-=vec2(0.5);
coord=rotate(u_time*5.0)*coord;
coord+=vec2(0.5);

float poly=polygon(coord,.3,8.0);

color+=vec3(poly);
gl_FragColor=vec4(color,1.0);
}

```

**Comment by patriciogonzalezvivo** [comment]
Hi! I think there is still a bit of confusion with the terms:

X11: is the underlying layer under windows managers on linux. If you run `startx` you are running X11
GLFW: it's a library that creates the OpenGL ES context for X11 enviroments
headless: is when you run a computer with no monitor or screen.
headless rendering: rendering something with no visible windows or viewport

For what you describe seams you compile your glslViewer with default `legacy` drivers. If you compiled glslViewer with `glfw` I recommend recompiling with the default legacy;

```
cd glslViewer
make clean
make
sudo make install
```

Those default `legacy` drivers don't need X11 ( aka do not do `startx glslViewer ...` and extra display arrangements). 
Once the RPi loads you just need to type:

```
glslViewer test.frag
```

Let's test that first and see what happens.

Note: I just tried that code in my laptop and works fine... later I can try it on a RPi 3 B+ to be extra sure.

**Comment by BjarneJensen** [comment]
Hey, Thanks! You are right about the confusion, but it is becoming clearer now. I already have tried the legacy way and it works as expected. No issues there. Great job on your part. I was hoping to compare performance between the two versions. I do not mind launching the x11 environment if it is necessary for rendering a GLFW window (I already do this for ofx apps I think). So with your clarification, I think I would like to 

```
1. start the pi in headless/CLI mode (no desktop, but connected to external monitor), 
2. launch the x11 context via ssh, 
3. export DISPLAY=:0 
4. start glslViewer(GLFW) window on external monitor
```
This works, but as far as I can tell I have to wait for the x11 environment to start so I can export the display environment variable, or it will not animate. So I just made this script, which seems to work but is maybe not the best solution. 
```
#!/bin/bash
X :0 &
export DISPLAY=:0.0 
/home/pi/glslViewerGLFW/bin/glslViewer ~/test.frag 
```
Can you think of a better method for accomplishing this? Anyway thanks for all the help and the awesome tool!
