### ISSUE TITLE
Adding AVFoundation drivers for macos webcam/mic support

### ISSUE THREAD

**Issue by nicolevella** [patriciogonzalezvivo/glslViewer#199]
Macbook webcams are no longer accessible via /dev/video*

They are using AVFoundation drivers.

https://developer.apple.com/av-foundation/

How can I access the webcam on my macbook? any ideas? i'm new to shaders, but I learn fast.

**Comment by patriciogonzalezvivo** [comment]
glslViewer shader.frag --video 0
Pleas read more here https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-video-support#on-macos

**Comment by nicolevella** [comment]
cool thx
