### ISSUE TITLE
compile error on Ubuntu 14.04

### ISSUE THREAD

**Issue by jasjuang** [patriciogonzalezvivo/glslViewer#20]
I followed the installation instruction and I am getting compilation error

g++ -o glslViewer -Wl,--whole-archive include/tinyobjloader/tiny_obj_loader.cc src/app.o src/main.o src/utils.o src/3d/camera.o src/3d/node.o src/gl/shader.o src/gl/texture.o src/gl/vbo.o src/gl/vertexLayout.o src/types/mesh.o src/types/polarPoint.o src/types/polyline.o src/types/rectangle.o src/types/shapes.o src/ui/cursor.o -L/usr/local/lib -lglfw3 -lGLU -lGL -lXrandr -lXi -lXxf86vm -lXcursor -lXinerama -lXrender -lX11 -lXext -lXdamage -lXfixes   -lpthread  -Wl,--no-whole-archive -rdynamic
/usr/bin/ld: /usr/local/lib/libglfw3.a(glx_context.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [glslViewer] Error 1

Could you let me know how to solve this? 

P.S: Would it be possible to have a cmake file for this so it can also work on windows?

**Comment by patriciogonzalezvivo** [comment]
Hello @jasjuang, I just upload a fix for ubuntu 64Bits

**Comment by patriciogonzalezvivo** [comment]
can you try it?

**Comment by jasjuang** [comment]
I am able to compile it successfully now, thanks!
