### ISSUE TITLE
Compiling from src on debian in a VM "Failed To Open Display"

### ISSUE THREAD

**Issue by nicolevella** [patriciogonzalezvivo/glslViewer#200]
ok, i think I got it compiled 

when I run glslViewer, I get this error

root@debian:/home/nicole# glslViewer shader.frag
No protocol specified
GLFW error 0x10008: X11: Failed to open display :0
ABORT: GLFW init failed

**Comment by nicolevella** [comment]
nevermind, Im an idiot hahahah

**Comment by patriciogonzalezvivo** [comment]
It's ok to close this issue @nicolevella ??
