### ISSUE TITLE
h264 encoded video files with extension .h264 doesn't work on my RPI B3+

### ISSUE THREAD

**Issue by bespsm** [patriciogonzalezvivo/glslViewer#203]
I tried to compile the latest master and got negative result.
Not sure though if this feature is fully ready: https://github.com/patriciogonzalezvivo/glslViewer/pull/202

I renamed file's extension to .mp4 and it worked (compiled with AV)

**Comment by patriciogonzalezvivo** [comment]
Do you mind expanding on what the negative results looks like?
Are you using `/opt/vc/src/hello_pi/hello_video/test.h264` ?? I notice I'm having some issues to detect the correct withxheight of the video stream.

If you change the `.h264` extension it use ffmpeg which is significantly slower because the decoding happens on the CPU

**Comment by bespsm** [comment]
Negative result is a launched shader but without rendered video (I attach .frag file). 
[test.frag.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/6119441/test.frag.txt)
With `/opt/vc/src/hello_pi/hello_video/test.h264` it works as you said it plays slower. BTW the image is flipped to 180 degree and mirrored ;). I also spotted that if you change RPI resolution to lower one, `test.h264` rendered faster.

Here is ffmpeg info for for my testing files, worked only `test.h264`:
`test.h264`: Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc

`VID_111.h264`: Stream #0:1(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 720x720, 1476 kb/s, 9.54 fps, 90k tbr, 90k tbn, 180k tbc (default)

`VID_222.h264` Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1:1 DAR 427:240], 883 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)

as you see they all have the same encoding, different details though

**Comment by bespsm** [comment]
with explanation it works,
https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-video-support
