### ISSUE TITLE
Asynchronously writing images to disk

### ISSUE THREAD

**Issue by ben-hansske** [patriciogonzalezvivo/glslViewer#207]
Currently the sequence command writes the images synchronously to disk. It seems that this is very slow. Therefore I tried to speed up the process by using rvaser's [thread pool implementation](https://github.com/rvaser/thread_pool). The results have been quite impressive so far. By using 5 threads to save the images (the number is picked arbitrary), I measured a speedup of roughly 2.8x on my laptop.

Synchronous:
```
time glslviewer -w 1920 -h 1080 --nocursor --headless -e "sequence,0,10,60" -e "q" mandelbox.frag
// [ ################################################## ] 100%
// >
________________________________________________________
Executed in  349.76 secs   fish           external
   usr time  257.14 secs  503.00 micros  257.14 secs
   sys time    3.08 secs  201.00 micros    3.07 secs
```

Asynchronous:
```
time ../bin/glslViewer -w 1920 -h 1080 --nocursor --headless -e "sequence,0,10,60" -e "q" ~/Dokumente/cxx/shaders/mandelbox.frag
// [ ################################################## ] 100%
// >
________________________________________________________
Executed in  122.66 secs   fish           external
   usr time  231.10 secs  880.00 micros  231.10 secs
   sys time    2.36 secs    0.00 micros    2.36 secs
```

I hope to be able to submit a pull request soon!

**Comment by patriciogonzalezvivo** [comment]
Oh nice! this numbers looks fantastic! Congratulations! I'm excited for this PR! 
One little thing, please double check that u_frame and u_time are still consistent. So the first image of the sequence have u_frame = 0, and u_time ~= 0.0 ... the second frame u_frame = 1, etc.

**Comment by patriciogonzalezvivo** [comment]
Feature added!
