### ISSUE TITLE
Strange behaviour when adding texture with name 

### ISSUE THREAD

**Issue by GRIM2D** [patriciogonzalezvivo/glslViewer#22]
main.fsh:
```
uniform sampler2D u_tex0;
uniform vec2 u_tex0Resolution;

void main() {
	vec2 currentCoord = vec2(gl_FragCoord.x / u_tex0Resolution.x, gl_FragCoord.y / u_tex0Resolution.y);
	vec4 pixel = texture2D(u_tex0, currentCoord);
	gl_FragColor = pixel;
}
```

terminal:
```
$ glslViewer main.fsh 01.jpg
```
output:
![screen shot 2015-10-13 at 9 51 45 am](https://cloud.githubusercontent.com/assets/6705445/10445771/607dd9b4-7190-11e5-8493-18ea021095c3.png)

terminal:
```
$ glslViewer main.fsh -tex0 01.jpg
```
![screen shot 2015-10-13 at 9 52 07 am](https://cloud.githubusercontent.com/assets/6705445/10445781/789b058a-7190-11e5-9d17-07afdf9554b7.png)

**Comment by patriciogonzalezvivo** [comment]
Hi @GRIM2D, that behavior makes sense because the uniform name is ```u_tex0``` and not ```tex0``` try with:

```bash
glslViewer main.fsh -u_tex0 01.jpg
```

**Comment by GRIM2D** [comment]
You're right. Using `-u_tex0` makes it work properly. But in console I see this:
```
$ glslViewer main.fsh -u_tex0 01.jpg
Loading 01.jpg as the following uniform: 
    uniform sampler2D u_u_tex0; // loaded
    uniform vec2 u_u_tex0Resolution;
```

Why glslViewer logs it as `u_u_tex0` ?

**Comment by patriciogonzalezvivo** [comment]
I see... I need to fix the console out is not accurate

**Comment by patriciogonzalezvivo** [comment]
This ( https://github.com/patriciogonzalezvivo/glslViewer/commit/7acb04f467df83632aee3ea1146ee5a0875825d8 ) should make it. 
Can you try it

**Comment by GRIM2D** [comment]
Now works correctly.
