### ISSUE TITLE
Preformance issues after prolonged use

### ISSUE THREAD

**Issue by nicolevella** [patriciogonzalezvivo/glslViewer#221]
I have a shader running on a Pi0.

After running for 7+ days, I am seeing noticeable frame rate dropping. Easily fixed with a sudo reboot. But just wanted to make note of this.

Not sure how I can provide any errors or anything. I think its just a matter of the low end hardware.

**Comment by patriciogonzalezvivo** [comment]
Hi! That would be a great case study to improve performance. I would start by updating GlslViewer to the latest version (if it's not) just to make sure is not something we already fix in master. Then if you don't mind mailing me the code I can take a look to it and run it at home to do further testing. My mail is patriciogonzalezvivo at gmail dot com

Thanks for surfacing this!!!

**Comment by nicolevella** [comment]
I will reset the pi and update glslviewer and also send you the code asap!

**Comment by nicolevella** [comment]
Ok, after LOTS of testing. I think this is an issue with Raspberry Pi and not glslViewer. I do not see the same performance loss on my PC as I do on my Pi.

I'll add an auto-reboot script as a cron job to fix this issue.

making closed.

**Comment by patriciogonzalezvivo** [comment]
Do you notice the performance loss only on the Pi Zero?

**Comment by nicolevella** [comment]
Indeed, I only noticed it on the zero.
