### ISSUE TITLE
glslViewer not starting when compiled with "make LIBAV=true"

### ISSUE THREAD

**Issue by TimPietrusky** [patriciogonzalezvivo/glslViewer#222]
I can execute `make LIBAV=true` without any problem, but when I try to start "glslViewer", I see this "error" and the app is not starting: 

```
glslViewer 
zsh: killed     glslViewer
```

## Steps to reroduce

* Follow the steps from https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-Audio-and-Video-support#macos
* Run `glslViewer`
* See error message from above

## Additional Information
 
When I compile glslViewer without `LIBAV=true` then it runs without any problem.

**Comment by TimPietrusky** [comment]
@patriciogonzalezvivo do you have any idea on how I can get some error messages to find out what could be wrong?

**Comment by patriciogonzalezvivo** [comment]
Maybe is related to https://github.com/patriciogonzalezvivo/glslViewer/issues/219#issuecomment-839776568 ??
`libav` is a lot of different libraries. `ffmpeg` is one of the main programs that use those libraries

**Comment by TimPietrusky** [comment]
@patriciogonzalezvivo after removing glslViewer again and running all steps from https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-Audio-and-Video-support#macos again it suddenly started to work. 

I guess something must have been outdated somewhere, so restarting my terminal was also a good idea :D
