### ISSUE TITLE
How to change the audio-input source to something that is not the mic?

### ISSUE THREAD

**Issue by TimPietrusky** [patriciogonzalezvivo/glslViewer#223]
When I pipe in audio into my visuals I usually use some virtual audio interface (like Blackhole) to pipe the system audio into my visuals software which can this then use as an audio input. 

Is there a possibility to do something like this also with glslViewer or is the mic "hardcoded" into it?

**Comment by bespsm** [comment]
I assume to make it work with BlackHole it should be seen in "Core Audio" and moreover BlackHole device should be also selected as default capture device, but I cannot say for sure

**Comment by bespsm** [comment]
Let's see, to avoid inconvenience I'll try to add verbose message that lists all available capture devices and an option to start with specific one

**Comment by TimPietrusky** [comment]
@bespsm that sounds super awesome, thank you very much!

**Comment by bespsm** [comment]
@TimPietrusky could you test this PR on your PC?

https://github.com/patriciogonzalezvivo/glslViewer/pull/226

**Comment by TimPietrusky** [comment]
@bespsm I just tested this on my Mac in combination with BlackHole and it's working perfectly. Thank you very much!

**Comment by bespsm** [comment]
nice, works for me too. I'll let you know when things get merged

**Comment by bespsm** [comment]
PR is merged, I guess we can close the issue

**Comment by TimPietrusky** [comment]
@bespsm I just tested the main branch and it also works. 

I guess what needs to be done now is to update the documentation, especially https://github.com/patriciogonzalezvivo/glslViewer/wiki/Using-GlslViewer as the `--audio` is not mentioned there at all.

**Comment by bespsm** [comment]
I agree, audio is not covered in the main and wiki pages, there is a small portion of info here though: 

https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-Audio-and-Video-support

**Comment by TimPietrusky** [comment]
@bespsm yeah, that small bit should be extended so that it's very clear to anyone that wants to use this, how it is actually working and what kind of data a user can expect when working with this.

**Comment by patriciogonzalezvivo** [comment]
I update some of the documentation on https://github.com/patriciogonzalezvivo/glslViewer/wiki/Using-GlslViewer#4-other-arguments
Please jump in and fill any gaps you find

**Comment by TimPietrusky** [comment]
@bespsm would you mind to add a section "working with audio" that somehow describes the audio-part a bit more in detail?

**Comment by bespsm** [comment]
I messed up a bit. Ok, since audio is an experimental feature, I extended description here:

https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compiling-with-Audio-and-Video-support

**Comment by TimPietrusky** [comment]
@bespsm thank you very much! Is there any way that we could talk directly with each other? Maybe via the Discord of https://shader.zone? I would love understand in detail how this works and what the data looks like, so that I can use this even more in detail for my live streams.
