### ISSUE TITLE
Link error in Windows 10

### ISSUE THREAD

**Issue by zgyijg** [patriciogonzalezvivo/glslViewer#227]
Hi, I use vs2019 to compile in Windows 10.

All previous operations are all correct, but in the last step, when i trying to open glslviewer.sln and compile it. There is a link error. error information is:

Error	LNK2019	unresolved external symbol _extract_depth referenced in function "public: bool __thiscall Uniforms::addTexture(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct WatchFile,class std::allocator<struct WatchFile> > &,bool,bool)" (?addTexture@Uniforms@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AAV?$vector@UWatchFile@@V?$allocator@UWatchFile@@@std@@@3@_N2@Z)	glslViewer	D:\OpenGLDev\Projects\glslViewer\uniforms.obj	1

please help to advise, thanks!

**Comment by smallfly** [comment]
I have the same issue. 

It seems that the definition of the 'extract_depth' function can not be found, even though it's clearly in the 'extract_depth.cpp'. I have not add the time to look at this more in details but it's likely it has something to do because it is an 'extern "c"'.

**Comment by patriciogonzalezvivo** [comment]
Cool, I will ask a Win dev for help.

**Comment by mihaisebea** [comment]
check if this fixes windows and doesn't break linux
https://github.com/patriciogonzalezvivo/glslViewer/pull/229

**Comment by smallfly** [comment]
It fixes the issue on Windows. I can not check on Linux. Thank you!

**Comment by patriciogonzalezvivo** [comment]
I can confirm it's working on Linux and MacOS (arm64). @mihaisebea is the best!
