### ISSUE TITLE
Support higher versions of GLSL

### ISSUE THREAD

**Issue by theottm** [patriciogonzalezvivo/glslViewer#235]
Hi ! This tool is awesome, simple yet powerful, thanks for sharing and also for the rest of your work.

I can achieve almost everything I fancy with glslViewer. The only limitation I have is that only glsl 120 is supported. Would it be complicated to  enable use of newer versions ?

For context : I'm trying to learn some particle systems stuff, mostly inspired by examples from shadertoy and they heavily use bitwise operations and textureSize or textureLod to process particle data stored in the buffer.

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks for your nice words about the tool. Have you tried adding `#version ` following by the version number you need as the first line? I'm a dinosaur that use older version of GLSL but I remember other people adding support for later versions already.

On that note I have been playing with particle systems my self. Recently added a 3D particle system. Check 
* https://github.com/patriciogonzalezvivo/glslViewer/blob/main/examples/3D/04_vertex/gpgpu.frag
* https://github.com/patriciogonzalezvivo/glslViewer/blob/main/examples/3D/04_vertex/gpgpu.vert

Try it by running the following command int that folder:

```
glslViewer pcl.ply gpgpu.vert gpgpu.frag -e buffers,on -l 
```

Note: I'm visualizing buffers with the command `buffers,on`, you can turn them off with `buffers,off`.

I'm now working on a 2D physarum particle system, which I will make public soon. Hope all this helps.

**Comment by theottm** [comment]
Hi, thanks for the quick answer ! I added the `#version ` trick. Apparently the versions supported are `1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, and 3.10 ES` but I guess this depends on my driver not glslViewer itself, right ?
Anyway with `#version 310 es` all the functions and operations I mentioned are now accepted, but I get a bigger problem : 
```
'gl_FragColor' undeclared
```
I come to think that this might be a problem with my driver ... Any clue maybe ?

**Comment by patriciogonzalezvivo** [comment]
This might help https://www.shaderific.com/blog/2014/3/13/tutorial-how-to-update-a-shader-for-opengl-es-30

**Comment by theottm** [comment]
Oh and I already tried this particle system example from you, pretty neat ! But I didn't know about the buffer command, that's useful, thanks !

**Comment by patriciogonzalezvivo** [comment]
the command visualize it... you create them with the `#if defined(BUFFER_X)`

**Comment by theottm** [comment]
Thanks for the reference. I tried replacing `gl_fragColor` with `fragmentColor` but still get the same error.

Also if I try a minimal shader like this 
```
#version 310 es
precision mediump float;
void  main(void) {}
``` 
I get `Error linking shader: error: all shaders must use same shading language version`

**Comment by theottm** [comment]
This also ends up in the same error I last mentioned. 
```
#version 310 es
precision mediump float;
out vec4 fragmentColor;
void  main() {
  fragmentColor = vec4(1);
}
```

**Comment by patriciogonzalezvivo** [comment]
The error is making reference that you need to create a vertex shader on the same language.

Related to you original motivation, I just added a Physarum example together with the 3D particle system, both are consider GPGPU examples https://github.com/patriciogonzalezvivo/glslViewer/blob/main/examples/3D/04_vertex/Makefile#L13-L17

**Comment by theottm** [comment]
Ah I see ! It almost works now. I created a default vertex shader that uses es310, adapting it  from the default vertex shader and used it in the glslViewer command.
The only moment when it breakes is when running multiple buffers.
The call to `ifdef BUFFER_0` leads again to the error `Error linking shader: error: all shaders must use same shading language version`

**Comment by theottm** [comment]
Very nice example btw ! I had fun playing with it.
The approach is different from what I have seen so far on shadertoy, since it uses the vertex shader and a point cloud. It's very interesting.
You actually compute the end result for all the particles, independent of the `population` variable, right ? You just hide a part of them using the `visible` variable, isn't it ?

**Comment by patriciogonzalezvivo** [comment]
Exactly! 

About https://github.com/patriciogonzalezvivo/glslViewer/issues/235#issuecomment-873242336, it makes sense because the default vertex shader use for buffer still on 120. This is a good case to add different default vertex shaders based on the version the frag is running. Do you mind sharing the vertex 310 es shader you are using so I start from there?

**Comment by theottm** [comment]
Yes that makes sense. Here is the vertex shader :
```
#version 310 es
precision mediump float;

uniform mat4 u_modelViewProjectionMatrix;

in vec4  a_position;
out vec4    v_position;

#ifdef MODEL_VERTEX_COLOR
in vec4  a_color;
out vec4    v_color;
#endif

#ifdef MODEL_VERTEX_NORMAL
in vec3  a_normal;
out vec3    v_normal;
#endif

#ifdef MODEL_VERTEX_TEXCOORD
in vec2  a_texcoord;
out vec2    v_texcoord;
#endif

void main(void) {
    
    v_position = a_position;
    
#ifdef MODEL_VERTEX_COLOR
    v_color = a_color;
#endif
    
#ifdef MODEL_VERTEX_NORMAL
    v_normal = a_normal;
#endif
    
#ifdef MODEL_VERTEX_TEXCOORD
    v_texcoord = a_texcoord;
#endif
    
    gl_Position = u_modelViewProjectionMatrix * v_position;
}
``` 
This is strictly the same as the default vertex shader in `glslViewer/src/shaders/default.h` with `attribute` replaced by `in` and `varying` replaced by `out`.

**Comment by patriciogonzalezvivo** [comment]
Ok, I made this PR that should bring support to all versions supported by your driver. 

https://github.com/patriciogonzalezvivo/glslViewer/commit/b40054bd7d7f5f3d68245f15d1748690063cb88c

With it you should need to make a special vertex shader, it will create a default one like before but for your version. Similarly to buffers vertex... probably I will need to extend this to the convolution pyramids, FXAA and holoplayer. But for the moment you trying it will be super helpful

**Comment by theottm** [comment]
It works ! I can now run multiple passes without any problem. Hurray !

**Comment by patriciogonzalezvivo** [comment]
fantastic!
