### ISSUE TITLE
Can't get OSC to work

### ISSUE THREAD

**Issue by ErikOostveen** [patriciogonzalezvivo/glslViewer#236]
Trying to get OSC to work on my Raspberry Pi Zero but probably overlooking something.

So, I installed pyOSC and created these two .py files to test OSC (over localhost:8000)

OSCtx.py, which transmits over OSC a value for u_redControl from 0.0 to 1.0 in 11 steps - one step every second.
-------------------------------------------------------------------------
import OSC
import time

c = OSC.OSCClient()
c.connect(('127.0.0.1', 8000))

oscmsg = OSC.OSCMessage()
oscmsg.setAddress("/u_redControl")

value = 0.0;

x = range(11)
for n in x:
  print(value)
  oscmsg.append(value)
  c.send(oscmsg)
  value = value + 0.1
  time.sleep(1)

--and, running in another SSH terminal (same raspberry), the "receiving file"; OSCrx.py
-------------------------------------------------------------------------
import OSC

def handler(addr, tags, data, client_address):
    txt = "OSCMessage '%s' from %s: " % (addr, client_address)
    txt += str(data)
    print(txt)

if __name__ == "__main__":
    s = OSC.OSCServer(('127.0.0.1', 8000))
    s.addMsgHandler('/u_redControl', handler)
    s.serve_forever()

--When I run this, I can see that it all works nicely:
![Capture](https://user-images.githubusercontent.com/40121318/123800927-af95bf80-d8e1-11eb-8361-81068ee52633.PNG)

So, next, I created this follow test .frag (OSCtest.frag:
(u_redControl here controls the red component of a simple plain screencolor)
-------------------------------------------------------------------------
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform float u_redControl;

varying vec4 v_position;
varying vec4 v_color;
varying vec3 v_normal;
varying vec2 v_texcoord;

void main (void) {
    vec2 st = gl_FragCoord.xy/u_resolution.xy;
    float aspect = u_resolution.x/u_resolution.y;
    st.x *= aspect;

    vec3 color = vec3(0.0);
    color.r = u_redControl;
    color.g = 0.2;
    color.b = 0.2;

    gl_FragColor = vec4(color,1.0);
}

--Then a ran:
glslViewer OSCtest.frag -l -p 8000

.. and ran OSCtx.py ... this is what I get ("OSC.OSCClientError: while sending: [Errno 111] Connection refused"):

![Capture_testOSC](https://user-images.githubusercontent.com/40121318/123802619-68103300-d8e3-11eb-8b17-86b76ee5a62b.PNG)

-- anyone knows what might be going on here? (I zipped the three files ... if others can try; would be great!)

[OSC_Test.zip](https://github.com/patriciogonzalezvivo/glslViewer/files/6733628/OSC_Test.zip)

**Comment by ErikOostveen** [comment]
I just spotted the following error whenever I use the -p option:

![Capture_Error](https://user-images.githubusercontent.com/40121318/123860021-49c72900-d91d-11eb-9d5d-d5d2d44e871e.PNG)

... what does this indicate?

**Comment by patriciogonzalezvivo** [comment]
Seams that you are running an old version of glslViewer. Did you compile from the repository? Do you mind showing the version number?

**Comment by ErikOostveen** [comment]
Thanks for that hint. I have version 1.7.0

I noticed that, for some reason, I over looked the install of the following:

sudo apt-get install libegl1-mesa-dev libgbm-dev libgles2-mesa-dev libdrm-dev

... I now get all options and OSC is working! good stuff! Great project!

**Comment by patriciogonzalezvivo** [comment]
YAY
