### ISSUE TITLE
Error while compiling on linux

### ISSUE THREAD

**Issue by leiserfg** [patriciogonzalezvivo/glslViewer#238]
It complains as [this call](https://github.com/patriciogonzalezvivo/glslViewer/blob/b7af3f2aef9beaa75a2a9a5f15cb075ad6a99da5/src/scene/light.cpp#L90) does not match this [signature](https://github.com/patriciogonzalezvivo/glslViewer/blob/817c2961091071328f980d990dcbac8fc502a1c2/src/gl/fbo.cpp#L77)

**Comment by patriciogonzalezvivo** [comment]
Do you mind copy&paste the error? Also what version of glslViewer you are trying to compile and the linux distribution you have?

**Comment by leiserfg** [comment]
Never mind, I just tested it on my laptop and it worked fine. I will close the issue and if it fails again on my PC (where I got the error yesterday) I will reopen it with more details.

**Comment by patriciogonzalezvivo** [comment]
cool! thanks
