### ISSUE TITLE
OSC Improvements

### ISSUE THREAD

**Issue by ErikOostveen** [patriciogonzalezvivo/glslViewer#239]
Hi, two quick notes (re. GlslViewer 1.7.0)

1. Would be great if in OSC listening mode, you can disable verbose output

2. Can precision be set? I only see 3 digits after the comma in the verbose output even though I am sending at 6 digits after the comma (see pic below - TX is what's being sent)

![CaptureOSC](https://user-images.githubusercontent.com/40121318/128531911-f57cb5eb-626c-4559-89c7-45a0f4aefc02.PNG)

**Comment by patriciogonzalezvivo** [comment]
Great feedback! I will look into it. To precise:

1. You would be interested on not seeing any output? except when `--verbose` is pass as an argument? or is just the feedback saying "OSC listening at localhost:8000" the issue? 

2. I will look into it... I believe the data is pass correctly to the shader and the precision issue is just when printing the output.  You can double check it by using https://github.com/patriciogonzalezvivo/lygia/blob/main/draw/digits.glsl this to visualize the content of `u_manual`.

**Comment by ErikOostveen** [comment]
Hi -

1. It would only be to disable OSC output after it says "OSC listening at localhost:8000"
2. Ok. Not sure exactly how to run the .glsl but I take your word for it that glslViewer passes all digits after the comma :-) ... it looks like it does indeed do that; just wanted to be sure.

This is a great project --- putting some stuff online in which I am using glslViewer for an electronics/visuals project:
https://twitter.com/ErikOostveen/status/1418983124638257152

**Comment by patriciogonzalezvivo** [comment]
Do you mind trying this? 

- https://github.com/patriciogonzalezvivo/glslViewer/commit/4215689f98f1faf787e5af824998e661fa7a4b67 
- https://github.com/patriciogonzalezvivo/glslViewer/commit/8765a6950fbbcbcb6294bcf989d4c5884b2f8dc3

if you use `--verbose` at the beginning should show the values with higher precision

Let me know how it goes.

Btw I love what you are making!

**Comment by ErikOostveen** [comment]
Hi - 

I did a git pull and spotted the changes ... but it looks like it's still only showing 3 digits [Rx] after the comma (but I am sending [Tx] 5 digits after the comma) ... perhaps I am using --verbose incorrect(?)

![Capture_OSC](https://user-images.githubusercontent.com/40121318/128635526-f01f1f06-adfc-4976-a91e-902f9e8652de.PNG)

**Comment by patriciogonzalezvivo** [comment]
Hi @ErikOostveen, change the integration with liblo, the issue should be solve now. Do you mind doing a clean clone/compile rutine. Here are the instructions https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-linux#raspberrypi-os-without-x11

**Comment by patriciogonzalezvivo** [comment]
weird... did you recompile and reinstall? After that

```
glslViewer <shader.frag> -p 8000 --verbose
```

Should show you what's arriving to port 8000
