### ISSUE TITLE
[Arch] Compilation error fixed - window.cpp

### ISSUE THREAD

**Issue by 0x-BAD** [patriciogonzalezvivo/glslViewer#241]
When compiling from source or by AUR helper `yay` i can't get compilation done.
Fortunately `make` tell me that there an `#include` directive missing on `src/window.cpp`

i have added at line `15` on file `src/window.cpp`:
```
#include <cstring>
```
and now compile without errors! Hope this fixes compilation error for some users in the meantime that the source code on the repository was updated. You're welcome!

**Comment by patriciogonzalezvivo** [comment]
Thank you!

**Comment by patriciogonzalezvivo** [comment]
Like this https://github.com/patriciogonzalezvivo/glslViewer/commit/5958d0671c2681c8faab9681d5ca13eaf792298f ??
