### ISSUE TITLE
Problems running on Windows using Powershell

### ISSUE THREAD

**Issue by LoganLang** [patriciogonzalezvivo/glslViewer#243]
I've followed the setup instructions for Windows but I'm running into some strange problems. Using powershell, I will run glslViewer on one shader and it will open up only to close immediately. In another directory, I will open a shader and it will remain open but it does not have the ability to reload the shader if it's updated.

Using Git Bash, I do not bump into these problems and the app seems to work just fine.

**Comment by LoganLang** [comment]
Update: somewhat randomly glslViewer seems to be working with both Powershell/Git Bash but both of them sometimes bump into issues with reloading, making me have to load it again manually.

**Comment by CalvinWilkinson** [comment]
On windows I have been trying to use the -l or --life-coding switches but when I changed the shader code and save it in VSCode, the window does not update.

**Comment by patriciogonzalezvivo** [comment]
Hi, sorry for the late replay, there were some chances on the source code related to this. Do you mind recompiling glslviewer and giving it a try?
