### ISSUE TITLE
unable to do mac compile

### ISSUE THREAD

**Issue by radorossum** [patriciogonzalezvivo/glslViewer#250]
following the instruction the make step produces 

CMake Error at deps/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /Users/liubo/dev/glslViewer/deps/ada

  does not contain a CMakeLists.txt file.

**Comment by patriciogonzalezvivo** [comment]
seams you skip the step to clone the submodule 

```
git submodule init
git submodule update
```

**Comment by radorossum** [comment]
thanks, worked, d'oh
