### ISSUE TITLE
Cannot build with ffmpeg 4.0+

### ISSUE THREAD

**Issue by TsaiHao** [patriciogonzalezvivo/glslViewer#255]
My ffmpeg is build from version 4.2. some apis like `avcodec_decode_video2` are deprecated, and ada building will fail.
A solution is to check ffmpeg version in ada CmakeLists, and add control macro in `textureStreamAV.cpp`.

**Comment by patriciogonzalezvivo** [comment]
This now should be fixed on `ada` https://github.com/patriciogonzalezvivo/ada/issues/8
