### ISSUE TITLE
Very slow comparing to webgl

### ISSUE THREAD

**Issue by jnpatrick99** [patriciogonzalezvivo/glslViewer#256]
I'm running glslViewer with the shaders from GLSL Sandbox that is using webGL in Chrome on macOS Bug Sur 11.6 (Intel, MacPro) with 4K Monitor. The same shaders perform much slower than they do on the website. It's like 4x-10x slower. I copy code 1:1.

Is there a way to improve performance, disable postprocessing or something like that? Thank you.

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks for bringing this up. I will do some test to try to figure out:
- Do you mind sharing the url of the code? 
- What type of GPU have your computer?
- What version of GlslViewer are you running?

I do not have any real answer for the moment, but since Apple decide to deprecate OpenGL, things have been weird in Apple land. I'm not surprise if Chrome is actually using Metal as the backing render for WebGL which could be the reason of that performance boost. To explore that you can compile GlslViewer as a WASM app and run it on your browser (which will appear as a regular WebGL app to it).

**Comment by jnpatrick99** [comment]
Thanks! 

Here's one example:
https://glslsandbox.com/e#77885.0
But actually most of 3d & raymarching stuff is very slow in glslViewer. It runs perfectly smooth inside the web browser with 1x resolution and no fps limit. What I noticed though that webgl is less antialiased than glslViewer's version. 

The GPU is Radeon PRO 580X.

glslViewer version is 2.0.0 (compiled from the most recent source).

I'll try the WASM route. But to render Metal it should use Metal shaders right? I'm not sure if there's a fully automatic way of transpiling GLSL into Metal shaders.

**Comment by vade** [comment]
My gut is this is a retina pixel density issue, you're probably rendering ~ 4x more pixels in glslViewer

**Comment by jnpatrick99** [comment]
@vade is there a way to switch 4x off in glslViewer?

**Comment by vade** [comment]
https://www.glfw.org/docs/3.3/window_guide.html 

GLFW_COCOA_RETINA_FRAMEBUFFER

Im not entirely sure how helpful that is but in theory there's a way to flip it?

**Comment by vade** [comment]
Looks like this is auto set here

https://github.com/patriciogonzalezvivo/ada/blob/eeb0d5f211010c1942e34ed9645435a5a692ecd0/deps/glfw/src/window.c

you can check out both glslViewer and ada, change that to false for both cases, and recompile perhaps?

**Comment by jnpatrick99** [comment]
Thanks @vade 
I disabled it, recompiled but it didn't help. Still very slow. BTW webgl version works perfect on Retina.

**Comment by patriciogonzalezvivo** [comment]
Hi! GLFW on retina just make the context x2 bigger (or what ever the pixel density is, if the antialiasing on the browser looks probably means the pixel density is constant at 1?) 
Have you tried opening glslViewer at the half of the resolution of the screen (so it's similar to x1 of the browser) and check the performance?

**Comment by patriciogonzalezvivo** [comment]
Ok, took a look to glsl sandbox code and I can confirm. Not only glsl sandbox don't render at the right pixel density but the canvas is half the size of what it should be and then stretched out. This explains the aliasing, which at this point is just pixelation.

<img width="1835" alt="Screen Shot 2022-01-06 at 7 51 11 AM" src="https://user-images.githubusercontent.com/346914/148386106-9876821a-bd7e-41c9-a786-257a331dc42a.png">

In this image taken the dom size is 1183x1086 but the canvas size actually at the half of that 591x543 = That's a pixel density of 0.5. 
While on the other hand glslViewer on a retina have a pixel density of 2.

This explains how glsl sandbox out perform glslViewer by sacrificing render quality,. GlslViewer is doing x4 the work that glsl sandbox is doing. The raymarching code with the double nested loop (99x4) on a 4K screen can easily explain the x10 perf difference.

**Comment by jnpatrick99** [comment]
@patriciogonzalezvivo 
Thanks for the explanation! Oh wow, yeah definitely ``canvas`` in the html code is 0.5x resolution of the screen. That explains it all!

I pulled new code and tested your shader - works like a charm! Thanks a ton for the example!

One stupid question, is there a way to increase buffer0 size from 512x512?

**Comment by patriciogonzalezvivo** [comment]
hi! to change the resolution of the buffer you need to change the comment here for the resolution you want

```
uniform sampler2D   u_buffer0; // 512x512
```

And where the resolution is set:

```
#define iResolution vec3(512.0, 512.0 * u_resolution.y/u_resolution.x , 1.)
```

It's not 8bits, should be 32bits. I was playing with some of the color values, you should be able to bring back the original color and tone.
