### ISSUE TITLE
Problem compiling on mac

### ISSUE THREAD

**Issue by wonjiky** [patriciogonzalezvivo/glslViewer#257]
Hello. Really being intrigued reading the Book of Shaders!
I was following the compile instructions but cmake .. in the build folder gives me a command not found error.
Is there something I am missing?

thanks in advance.

**Comment by patriciogonzalezvivo** [comment]
Hi, do you mind sharing what kind of error you see and [which steps of this guide](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-MacOS) you have already follow?
