### ISSUE TITLE
Compile into a shared library

### ISSUE THREAD

**Issue by anastasiuspernat** [patriciogonzalezvivo/glslViewer#258]
Do you think there's a way to compile glslViewer into a shared macOS library? Wanted to make a simple macOS screensaver based on it with different shaders from shadertoy.

Also have to say wow - such an awesome, fast and easy to use OpenGL renderer! And also admire the amount of work and the ada library!

**Comment by vade** [comment]
You can probably use the GLSL library that @patriciogonzalezvivo wrote, which looks helpful and built for that, https://github.com/patriciogonzalezvivo/ada

**Comment by anastasiuspernat** [comment]
Yes! Thank you. That seemed to have solved it. Now I have another problem that screensaver's `NSView` always stays on top of any other window so `glfwCreateWindow` creates an invisible window. But that's a totally different problem.

**Comment by vade** [comment]
I suspect you'd need to adjust not calling glfwCreateWindow and maybe get a native pointer to an the NSWindows NSVIew and place in your own native NSOpenGLView or what not, then pass that native CGLContextObject to glfws so it can inherit the context (and thus the drawable) from the screen saver.


Alternatively you might be able to forgo making an NSWIndow, and letting glfwCreateWindow get called, and get a native pointer to the NSWindow instance and tell the screen saver "hey fucker use this one"

**Comment by anastasiuspernat** [comment]
Hahaha, thanks for the hint! The latter did it.
