### ISSUE TITLE
Is `brew upgrade` a good idea?

### ISSUE THREAD

**Issue by andyinabox** [patriciogonzalezvivo/glslViewer#26]
This is kind of nitpicky but does it really make sense to include `brew upgrade` in the Mac install instructions? On any machine with a large number of packages you might spend all day upgrading unrelated packages, or even upgrading packages that you might not want changed.

Seems like more of a "if it doesn't work, try running `brew upgrade` first"?

**Comment by patriciogonzalezvivo** [comment]
Very true! I guess my idea was a serie of instructions that most likely will set everything up to compile. Medium to advance user will read through and skip all the redundant part, while beginners... well... it will take longer but have better chances... 

I don't know. I will think about it. 

THANKS! is a good point
