### ISSUE TITLE
Can't compile on Linux PopOS

### ISSUE THREAD

**Issue by Simonoob** [patriciogonzalezvivo/glslViewer#262]
compiling from source  with `make` ([this step](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-linux#for-any-linux-x11-environment-uses-of-glfw-30)) gives the following error:
```
[ 47%] Building CXX object deps/ada/src/CMakeFiles/ada.dir/gl/textureStreamAV.cpp.o
/home/simonoob/Documents/projects/glslViewer/deps/ada/src/gl/textureStreamAV.cpp: In member function ‘virtual bool ada::TextureStreamAV::load(const string&, bool, ada::TextureFilter, ada::TextureWrap)’:
/home/simonoob/Documents/projects/glslViewer/deps/ada/src/gl/textureStreamAV.cpp:120:76: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
  120 |         input_lodaded = avformat_open_input(&av_format_ctx, _path.c_str(), ifmt, &options);
      |                                                                            ^~~~
      |                                                                            |
      |                                                                            const AVInputFormat*
In file included from /home/simonoob/Documents/projects/glslViewer/deps/ada/include/ada/gl/textureStreamAV.h:9,
                 from /home/simonoob/Documents/projects/glslViewer/deps/ada/src/gl/textureStreamAV.cpp:1:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2226:90: note:   initializing argument 3 of ‘int avformat_open_input(AVFormatContext**, const char*, AVInputFormat*, AVDictionary**)’
 2226 | int avformat_open_input(AVFormatContext **ps, const char *url, ff_const59 AVInputFormat *fmt, AVDictionary **options);
      |                                                                           ~~~~~~~~~~~~~~~^~~
make[2]: *** [deps/ada/src/CMakeFiles/ada.dir/build.make:238: deps/ada/src/CMakeFiles/ada.dir/gl/textureStreamAV.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:485: deps/ada/src/CMakeFiles/ada.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

```
Really not sure what this is about. I should have all the dependencies but maybe I'm missing something.

**Comment by patriciogonzalezvivo** [comment]
Do you mind sharing what OS and version of ffmpeg are you using?

**Comment by Simonoob** [comment]
Wow thank you for the super quick response :bow: . This is what I get from `ffmpeg -version`:
```
ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
```

**Comment by patriciogonzalezvivo** [comment]
Mmm.. this seems related to the recent update to ffmpeg 4.X 

Do you mind checking the version of `LIBAVFORMAT_VERSION_MAJOR`, `LIBAVFORMAT_VERSION_MINOR` from here  `libavformat/version.h`  and adapt it here https://github.com/patriciogonzalezvivo/ada/commit/93d6e9b39a944190e4a68e56eda128aa7a8d3a3a

If that's a lot knowing `LIBAVFORMAT_VERSION_MAJOR`, `LIBAVFORMAT_VERSION_MINOR` from  `libavformat/version.h` will be enough for me to try fix

**Comment by Simonoob** [comment]
I would love to help but I don't think I know enough to make the fix there. Anyway the versions from `libavformat/version.h` are:
`LIBAVFORMAT_VERSION_MAJOR  58`
`LIBAVFORMAT_VERSION_MAJOR  58`

**Comment by patriciogonzalezvivo** [comment]
Sorry for the delay, I made [a change on `ada` that I think will fix this](https://github.com/patriciogonzalezvivo/ada/commit/3f998ae6df7cac4aa301eacca33b1051f174cfc8). Please try:

```bash
cd glslViewer
git pull
git submodule update
cd deps/ada
git pull
cd ../../build
cmake ..
make
```

**Comment by Simonoob** [comment]
That solved it! Thank you so much for the quick support and the amazing tool :rocket:
