### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by billyberkouwer** [patriciogonzalezvivo/glslViewer#263]
When I try to compile the glslViewer.sln file, I get the following error.

> make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I am using Windows 10. I installed CMake through Scoop as requested.

Any help would be much appreciated.

**Comment by patriciogonzalezvivo** [comment]
Hi! Are you using [this instructions](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-Windows)? Did that prompt pop in Visual Studio? Or you are trying to compile from the terminal?

**Comment by billyberkouwer** [comment]
Hi, thanks for getting back to me! 

The prompt appeared when trying to compile from both the terminal and VS code. I think the issue had to do with cmake not knowing which generator to use. 

I could not find a way to resolve the error through terminal, however in the VS code interface I was able to select which generator to use and compile by pressing a button which didn't rely on the 'make' build command.

The generator now works v well. Thank you for your help!
