### ISSUE TITLE
Problem compiling on mac

### ISSUE THREAD

**Issue by sinewave440hz** [patriciogonzalezvivo/glslViewer#265]
Sounds identical to https://github.com/patriciogonzalezvivo/glslViewer/issues/257

When I follow the instructions for Mac compilation precisely, I encounter a problem when I get to the command `cmake ..` from the build directory. This gives me `zsh: command not found: cmake
` and I am of course unable to complete the build process. Presumably cmake is a prerequisite. I have downloaded the cmake binary and I suppose I'll need to set up the command line. But maybe this should be mentioned in the docs?

**Comment by sinewave440hz** [comment]
Yes those were the steps I was referring to. I see you just updated the docs, after which everything works fine. Thanks for the quick response!

**Comment by patriciogonzalezvivo** [comment]
awesome! yes, was missing the `cmake` library
