### ISSUE TITLE
`record` crashes with a memalloc error

### ISSUE THREAD

**Issue by leiserfg** [patriciogonzalezvivo/glslViewer#268]
It says `malloc(): corrupted top size` and the video files created (name.mp4  and name_000.mp4 ) are empty.

**Comment by patriciogonzalezvivo** [comment]
What's the full command?
Do you have ffmpeg installed on your system and is glslViewer compiled with support for it?

**Comment by leiserfg** [comment]
I just rebuilt the last commit on my laptop and it worked fine (previously was in my PC pointing to the latest release) so I will close the issue and try to recreate it again in my PC, sorry.

**Comment by patriciogonzalezvivo** [comment]
cool, glad it worked out

**Comment by leiserfg** [comment]
I'm back in the pc, the issue is happening here and is not ffmpeg related, the error happens in this line (yes I decided to check the C++ code after years without touching that lang :smile: )  
[`auto pixels = std::unique_ptr<unsigned char[]>(new unsigned char [width * height * 3]);`  ](https://github.com/patriciogonzalezvivo/glslViewer/blob/0072fd89c8c3031e8c3054cde03d5f87af307a10/src/sandbox.cpp#L1890)
I tried to split it (taking the creation of the array out like 
`auto a = new unsigned char [width * height * 3];` and it breaks there so I think it has something to be with my screen size (1440p)

**Comment by leiserfg** [comment]
I was trying to `valgrind` it, but couldn't find extra info besides that the allocation is failing, I tried to use a memory sanitizer but there are several memory leaks of 3rd parties (even x11) so it finishes prematurely and I couldn't reach the bug.

**Comment by patriciogonzalezvivo** [comment]
do you mind clarifying what's the command that trigger the error?

**Comment by leiserfg** [comment]
I'm just doing `record,asdf.mp4,0,1` . I debugged it and the crash happens while allocating the memory to store the screenshot but only happens in my PC (with a 1440 screen) and not on my laptop with a 1080p one.

**Comment by patriciogonzalezvivo** [comment]
I see... weird. Both runs linux, right?

**Comment by leiserfg** [comment]
Right

**Comment by patriciogonzalezvivo** [comment]
Mmm... The size of the screen shouldn't matter. it's only for recording mp4? whay happen when you make a PNG sequence?

```
sequence,0,1.
```

**Comment by leiserfg** [comment]
I just tested `sequence,0,10` and it worked fine.

**Comment by leiserfg** [comment]
btw, I verified that ffmpeg is working (I ran the test_video example)
