### ISSUE TITLE
press esc to close app?

### ISSUE THREAD

**Issue by firmread** [patriciogonzalezvivo/glslViewer#27]
maybe it's just my preference but I think having esc pressed and close the app is much more fail safe in fast iteration development. cmd+q is a little more destructive and I had to be quite cautious of closing sublime. while leaving the app on taking resource significantly so I have to close it pretty often.

**Comment by patriciogonzalezvivo** [comment]
True! Feel free to replace it here: https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/main.cpp#L424-L430

note: It had to work on OSX, ubuntu and raspbian

**Comment by dorald** [comment]
I just added a 'esc' key to close the app. [#30]
Also I've tested always on top referring to the issue/request [#28] by @firmread , but it does not seem a good idea when you want to open two or more glslViewer.

Hey @patriciogonzalezvivo thank you for making glslViewer ! :)

**Comment by patriciogonzalezvivo** [comment]
Hi @dorald thanks for the PR! I'm glad you like it :)
Question have you try compiling this on the RaspberryPi? That version doesn't use GLFW... we can use some `#ifdef` macros

**Comment by dorald** [comment]
Hi @patriciogonzalezvivo  .
I've tested on OS X , unfortunately I don't have Raspberry Pi :(

**Comment by dorald** [comment]
I think `getch()` will work on RP with macro.

**Comment by patriciogonzalezvivo** [comment]
Hi I will try it this week... want to make a PR with the macro?

**Comment by dorald** [comment]
Hi. I just added [PR](https://github.com/patriciogonzalezvivo/glslViewer/pull/30/commits/b887272e03a8ef9dd4667226305aa2746e2dcc33) with Raspberry Pi macro.
