### ISSUE TITLE
 Flow control statements are not properly nested. - MacOS M1

### ISSUE THREAD

**Issue by richardegil** [patriciogonzalezvivo/glslViewer#272]
I was experiencing the same issue in #270 and tried to follow the steps to resolve it.

Now I am getting an error :
```
CMake Error at CMakeLists.txt:208 (endif):
  Flow control statements are not properly nested.
```
Any suggestions?

![Screen Shot 2022-06-20 at 2 19 54 PM](https://user-images.githubusercontent.com/1187709/174666331-900c9c7c-59b0-42bc-b408-99d3313e7445.png)
![Screen Shot 2022-06-20 at 2 20 53 PM](https://user-images.githubusercontent.com/1187709/174666344-ad7d92bc-4572-420c-8bcc-711fc04d3fb1.png)

**Comment by richardegil** [comment]
Forgot to include machine details:
MacOS Monteray 12.4 M1 Pro

**Comment by patriciogonzalezvivo** [comment]
mmm... the lines have moved since then.
 Comment lines from 100 and 105.
That a side, have you installed ncurses with brew?

**Comment by richardegil** [comment]
@patriciogonzalezvivo yes, I installed that. Let me try commenting out the lines you mentioned.

**Comment by richardegil** [comment]
@patriciogonzalezvivo that seemed to work, I was able to run the test file successfully.

Thanks for the quick response!

**Comment by patriciogonzalezvivo** [comment]
Awesome, thank you
