### ISSUE TITLE
macOS: fails to open a preview window when run from iterm + tmux

### ISSUE THREAD

**Issue by nkaretnikov** [patriciogonzalezvivo/glslViewer#273]
Works with just iterm and terminal app + tmux. What details do I need to provide to help you debug?

**Comment by nkaretnikov** [comment]
I wonder if iterm just lacks some macOS specific permissions or something, but I have no idea where to look that up.

**Comment by patriciogonzalezvivo** [comment]
Hi! thank you. What do you mean with a preview window? like the main window?

**Comment by nkaretnikov** [comment]
@patriciogonzalezvivo i mean the window where the shader is displayed

**Comment by patriciogonzalezvivo** [comment]
Oh! That doesn't sound good. 
1. You mean start's and crash? 
2. Do you mind sharing the error message and arguments used to execute it?
3. Have you build from source, from the latest version on github? If yes, do you  mind running it with `--noncurses` I suspect ncurses is producing the error.

**Comment by nkaretnikov** [comment]
also: would be cool if there were an option to start it on foreground (and keep it on foreground as well) -- i could create another issue for that. haven't checked whether there are any already

**Comment by patriciogonzalezvivo** [comment]
If you lunch the glslViewer with the `-l` or `--life-coding` arguments will lunch in the foreground and stay that way. You can learn more about arguments here https://github.com/patriciogonzalezvivo/glslViewer/wiki/Using-GlslViewer#4-other-arguments

What kind of file are you trying to pass? do you have user privileges on that folder
