### ISSUE TITLE
Compile error in MacOS

### ISSUE THREAD

**Issue by zhengying** [patriciogonzalezvivo/glslViewer#278]
env: MacOS 11.6

Error info:
```
...
glslViewer/src/tools/text.cpp:90:21: error: chosen constructor is explicit in copy-initialization
        std::smatch match = {};
...
```
the compilation is successful after modified like this
 `std::smatch match = {}; ` to  
`std::smatch match = std::smatch()`;

**Comment by patriciogonzalezvivo** [comment]
@tcoyvwac do you mind taking a look?

**Comment by tcoyvwac** [comment]
Sure thing @patriciogonzalezvivo, @zhengying: what compiler / compiler version are you using? This will help in understanding your error.

**Comment by zhengying** [comment]
> Sure thing @patriciogonzalezvivo, @zhengying: what compiler / compiler version are you using? This will help in understanding your error.

compiler info:
Apple clang version 13.0.0 (clang-1300.0.29.3)

**Comment by tcoyvwac** [comment]
Thanks for reporting the Issue @zhengying! :tada: 
It seems that `Apple clang` has a particular quirk which is different from other compilers (even `clang` on other systems)!

There is no pre-check for `Apple clang` on PRs so it seems this `Apple clang` quirk slipped through code review. :smile_cat:

**Comment by patriciogonzalezvivo** [comment]
Hi! Is this fixed?
