### ISSUE TITLE
always on top option for os x?

### ISSUE THREAD

**Issue by firmread** [patriciogonzalezvivo/glslViewer#28]
I think it would help to make sure that I'm not running multiple windows. Especially while [https://github.com/patriciogonzalezvivo/glslViewer/issues/24] is still a problem.

**Comment by patriciogonzalezvivo** [comment]
Hi Firm, the bug on OSX where the glslViewer wasn't closing appropriately was solve.

**Comment by patriciogonzalezvivo** [comment]
Not sure how to resolve what you are saying. I usually open two or three glslViewer
