### ISSUE TITLE
can't compile on Fedora

### ISSUE THREAD

**Issue by renanmartins1813** [patriciogonzalezvivo/glslViewer#286]
I am following the Compile instructions for Linux; Installed all dependencies and upgraded the entire system but the error keeps occurring.

[cmake.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/9435080/cmake.txt)
[make.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/9435083/make.txt)
[makeInstall.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/9435085/makeInstall.txt)
[CMakeError.log](https://github.com/patriciogonzalezvivo/glslViewer/files/9435086/CMakeError.log)
[CMakeOutput.log](https://github.com/patriciogonzalezvivo/glslViewer/files/9435087/CMakeOutput.log)

**Comment by tcoyvwac** [comment]
Hi there @renanmartins1813,

Humm, on quick glance, 
`makeinstall.txt` and `make.txt` says, there is a problem in the linking stage...:
```
[ XXX %] Linking CXX executable glslViewer
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/12/../../../libncurses.so.6 when searching for libncurses.so.6
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/12/../../../libtinfo.so when searching for -ltinfo
/usr/bin/ld: skipping incompatible /lib/libtinfo.so when searching for -ltinfo
/usr/bin/ld: skipping incompatible /usr/lib/libtinfo.so when searching for -ltinfo
/usr/bin/ld: cannot find -ltinfo
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/12/../../../libtinfo.so when searching for -ltinfo
/usr/bin/ld: skipping incompatible /lib/libtinfo.so when searching for -ltinfo
/usr/bin/ld: skipping incompatible /usr/lib/libtinfo.so when searching for -ltinfo
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/glslViewer.dir/build.make:224: glslViewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:199: CMakeFiles/glslViewer.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by renanmartins1813** [comment]
Hello @tcoyvwac,

I managed to solve the problem using the following commands: 
```sudo dnf install ncurses-compat-libs ncurses-static```
```reboot```
```sudo ldconfig -v```
```reboot```

I am not sure which one did the trick but I'm glad that one of them did!

**Comment by patriciogonzalezvivo** [comment]
Oh! I'm glad it worked! I'm adding your findings to the documentation and 
 close this thread https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-Linux#fedora

If someone can verify that this instructions work, would be great
