### ISSUE TITLE
Library not found error on Mac OS

### ISSUE THREAD

**Issue by ManjitBedi** [patriciogonzalezvivo/glslViewer#293]
Hello, 

I've just downloaded & installed the project from GitHub following the Mac build instructions.

I get the following error when I run the  glslviewer application:

```
examples % glslViewer 2D/00_tests/test.frag
dyld[1239]: Library not loaded: '/usr/local/opt/glfw3/lib/libglfw3.3.dylib'
  Referenced from: '/usr/local/bin/glslViewer'
  Reason: tried: '/usr/local/opt/glfw3/lib/libglfw3.3.dylib' (no such file), '/usr/local/lib/libglfw3.3.dylib' (no such file), '/usr/lib/libglfw3.3.dylib' (no such file)
```

I'm using Mac OS version 12.6. I am using a MacBook Pro with the Apple M1 chipset.

**Comment by patriciogonzalezvivo** [comment]
Hi! Wonder if you compiled them from source or download a precompiled package.

**Comment by ManjitBedi** [comment]
I followed the instructions using Homebrew and compiled the various dependancies for NCurses & FFMPEG. 

I also tried installing the GLFW library with homebrew as you mentioned.  It is a different version number for the library from libglfw3.3.dylib.
 
 ```
/opt/homebrew/Cellar/glfw/3.3.8/include/GLFW/ (2 files)
/opt/homebrew/Cellar/glfw/3.3.8/lib/libglfw.3.3.dylib
/opt/homebrew/Cellar/glfw/3.3.8/lib/cmake/ (4 files)
/opt/homebrew/Cellar/glfw/3.3.8/lib/pkgconfig/glfw3.pc
/opt/homebrew/Cellar/glfw/3.3.8/lib/ (2 other files)
```
Is this relevant the 'opt' directory using on the M1 macs over using 'usr'?

**Comment by patriciogonzalezvivo** [comment]
You mean you install glslViewer using homebrew, like:
```
brew install glslviewer
```

**Comment by ManjitBedi** [comment]
Hi, I first did the install by compiling from the GitHub repo.  That did not work for me.

**Comment by ManjitBedi** [comment]
I think I have it working now; I needed to delete the binary in the '/usr/' path and then reinstalled it with Homebrew to the ' /opt/homebrew/bin/glslviewer' path.

**Comment by patriciogonzalezvivo** [comment]
That’s great news! Question:

- what went wrong compiling glslViewer from source? 

- do you mind checking what version of glslViewer it’s on brew?

**Comment by ManjitBedi** [comment]
Hi Patricio,

The version is:
``` /opt/homebrew/Cellar/glslviewer/2.1.2_1 (146 files, 48MB) ```

I don't recall seeing any compile errors with the source from GitHub but there was a warning installing nurses with Homebrew.

```
ncurses is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ncurses first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/ncurses/bin:$PATH"' >> ~/.zshrc

For compilers to find ncurses you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/ncurses/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/ncurses/include"

For pkg-config to find ncurses you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/ncurses/lib/pkgconfig"
```

**Comment by patriciogonzalezvivo** [comment]
Heads up you are running an older version, that we will use on this Tuesday workshop.
If you don't mind uninstalling the brew version and giving another go to following [this instructions to compile it from this repository would be great](https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-MacOS)
