### ISSUE TITLE
Could not install glsl viewer on Mac OS 12.6 - M1

### ISSUE THREAD

**Issue by peterknu** [patriciogonzalezvivo/glslViewer#295]
Hi,

this is what happening in Terminal when I follow the steps on this site https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-MacOS:

brew install pkg-config cmake ncurses

peter-vega@MacBook-Pro ~ % brew install pkg-config cmake ncurses
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)
	from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
	from /usr/local/Library/Homebrew/os/mac.rb:17:in `new'
	from /usr/local/Library/Homebrew/os/mac.rb:17:in `version'
	from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/brew.rb:10:in `<main>'

—

brew install ffmpeg --build-from-source

peter-vega@MacBook-Pro ~ % brew install ffmpeg --build-from-source
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)
	from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
	from /usr/local/Library/Homebrew/os/mac.rb:17:in `new'
	from /usr/local/Library/Homebrew/os/mac.rb:17:in `version'
	from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/brew.rb:10:in `<main>'

—

git clone https://github.com/patriciogonzalezvivo/glslViewer.git
cd glslViewer
git submodule init
git submodule update

peter-vega@MacBook-Pro ~ % git clone https://github.com/patriciogonzalezvivo/glslViewer.git
cd glslViewer
git submodule init
git submodule update
Cloning into 'glslViewer'...
remote: Enumerating objects: 11947, done.
remote: Counting objects: 100% (829/829), done.
remote: Compressing objects: 100% (264/264), done.
remote: Total 11947 (delta 583), reused 803 (delta 564), pack-reused 11118
Receiving objects: 100% (11947/11947), 193.97 MiB | 17.29 MiB/s, done.
Resolving deltas: 100% (7672/7672), done.
Submodule 'deps/vera' (https://github.com/patriciogonzalezvivo/vera.git) registered for path 'deps/vera'
Cloning into '/Users/peter_1/glslViewer/deps/vera'...
Submodule path 'deps/vera': checked out '0cbd1e6ca90530b8eb665c26864e7120466facca'
peter-vega@MacBook-Pro glslViewer % 

—

mkdir build
cd build
cmake ..
make
sudo make install

peter-vega@MacBook-Pro glslViewer % mkdir build
cd build
cmake ..
make
sudo make install
zsh: command not found: cmake
make: *** No targets specified and no makefile found.  Stop.
Password:
make: *** No rule to make target `install'.  Stop.
peter-vega@MacBook-Pro build %

**Comment by patriciogonzalezvivo** [comment]
Hi! Seams there problem is with brew. Is the first time you use it? Do you mind uninstalling it and install it again. Also maybe ask on their forums about that issues?

I can confirm that have install those dependencies in M1 without issues, that’s why my suspicions are that something is off w brew it self

**Comment by peterknu** [comment]
Hi,

it is the first time I use brew as I know. How do I uninstall it?

Thanks
-- 
Peter

> 17. okt. 2022 kl. 13:03 skrev Patricio Gonzalez Vivo ***@***.***>:
> 
> 
> Hi! Seams there problem is with brew. Is the first time you use it? Do you mind uninstalling it and install it again. Also maybe ask on their forums about that issues?
> 
> I can confirm that have install those dependencies in M1 without issues, that’s why my suspicions are that something is off w brew it self 
>

**Comment by patriciogonzalezvivo** [comment]
A quick google show me this one: https://appuals.com/install-and-uninstall-homebrew-on-macos/ 
To explain, `brew` it's a tool to install dependencies in a "linux" style. It's not intrinsically related to glslViewer. It's just the most common and used package manager for MacOS. So there are other ways, but requires more experience with C/C++ compiler and POSIX systems

**Comment by peterknu** [comment]
Hi

Seems ok now.

Thanks
-- 
Peter

**Comment by patriciogonzalezvivo** [comment]
Awesome! I will close this thread. Please don't hesitate to ask if something comes up again
