### ISSUE TITLE
Assets in 3.0.1 release are for older version

### ISSUE THREAD

**Issue by gmlewis** [patriciogonzalezvivo/glslViewer#298]
On this page: https://github.com/patriciogonzalezvivo/glslViewer/releases/tag/3.0.1
when you click on "Assets", the pre-compiled builds are for a 2.2 version, not 3.0.1.

**Comment by patriciogonzalezvivo** [comment]
Good catch... I messed up the released numbers... hopefully will match again in the coming 3.0.4 https://github.com/patriciogonzalezvivo/glslViewer/releases/

Thank you!

**Comment by patriciogonzalezvivo** [comment]
Fixed! https://github.com/patriciogonzalezvivo/glslViewer/releases/tag/3.0.4
