### ISSUE TITLE
Windows binary fails to launch. Missing dlls 

### ISSUE THREAD

**Issue by pajama** [patriciogonzalezvivo/glslViewer#304]
When launching the release binary on windows I get errors that the following dlls could not be found. 
swscale-5.dll
avformat-58.dll
avdevice-58.dll
avcodec-58.dll

Thanks for taking a look!

**Comment by patriciogonzalezvivo** [comment]
Duplicate of https://github.com/patriciogonzalezvivo/glslViewer/issues/305
