### ISSUE TITLE
Raspberry Pi windowed mode?

### ISSUE THREAD

**Issue by wraybowling** [patriciogonzalezvivo/glslViewer#31]
I'd like to be able to both view shaders with glslviewer on my raspberry pi and edit them in Vim. Ideas?

**Comment by patriciogonzalezvivo** [comment]
Installing [GLFW](https://github.com/patriciogonzalezvivo/glslViewer#installing-in-ubuntu) and forcing it to compile as linux instead of RPI

https://github.com/patriciogonzalezvivo/glslViewer/blob/master/Makefile#L37
