### ISSUE TITLE
glslviewer 3.0.8 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [patriciogonzalezvivo/glslViewer#313]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test error</summary>

```
    TypeError: no implicit conversion from nil to integer
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/3551605493/jobs/5965959624
relates to Homebrew/homebrew-core#116736

**Comment by chenrui333** [comment]
I can also reproduce the same issue against [the HEAD commit](https://github.com/patriciogonzalezvivo/glslViewer/commit/4234190460a3078c656ccdd7e9b6a2cee929a4af) as well

**Comment by patriciogonzalezvivo** [comment]
Hi! thanks for the heads up, do we know on what file and line that error type occur?

**Comment by chenrui333** [comment]
my bad, just need to update tests on our end per [this commit](https://github.com/patriciogonzalezvivo/glslViewer/commit/80784d6d11e492ed1bbf630f3310d18a6e9b6900)

**Comment by chenrui333** [comment]
@patriciogonzalezvivo filed a PR to cleanup old example code, let me know if that works for you.
