### ISSUE TITLE
Build glslViewer for Nvidia Jetson TK1 (Ubuntu 15.10)

### ISSUE THREAD

**Issue by raju-bitter** [patriciogonzalezvivo/glslViewer#32]
Installed Ubuntu 14.04 (Ubuntu 14.04.4 LTS) using JetPack TK1 1.2 (October 2015)
https://developer.nvidia.com/embedded/downloads

Followed the build instructions to build glfw (no build problems). Manually set the platform to LINUX in the Makefile, and then build glslViewer. No build errors.

When launching glslViewer with the bunny.frag, no window is opened; but no error is shown either. Control-C will quit glslViewer.

Update: Attached build log
[build.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/302755/build.txt)

**Comment by Mezzano** [comment]
Installed Ubuntu 14.04.5 LTS. No build errors for glfw and for glslViewer but we get a segmentation fault when launching glslViewer.

Attached build log.
[build.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/631528/build.txt)

**Comment by patriciogonzalezvivo** [comment]
What GPU hardware/drivers are you using? can you `dbg` it?

**Comment by Mezzano** [comment]
We're using GeForce GTX TITAN X with Driver Version: 367.57.

**Comment by patriciogonzalezvivo** [comment]
Any news on this?
