### ISSUE TITLE
Issues installing GLSL viewer using cmake

### ISSUE THREAD

**Issue by ElRafaVaz** [patriciogonzalezvivo/glslViewer#320]
Hi everybody!

I'm having a problem installing GLSL viewer. I'm following the instructions here: https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-Windows

and I've installed the latest scoop &, cmaker versions and have also kept this repo up to date. However, when I get to step 3 I get this error:

![image](https://user-images.githubusercontent.com/100080576/210151031-64d7138f-2316-44f8-921e-dcbc0c4b96aa.png)

I've tried going through the CMakeLists and cmake help to see what the issue is, but I'm not familiar with these tools and not sure what the issue could be.

Does anyone know where the issue could lie?

**Comment by patriciogonzalezvivo** [comment]
Seams you don't have cmake installed on your system. Alternatively, GlslViewer have binary releases you can download and install without having to compile

**Comment by ElRafaVaz** [comment]
I managed to get it to work with a binary release. Thanks for the help :)
