### ISSUE TITLE
'record' command crashes randomly with segfault error, macos m1 big sur

### ISSUE THREAD

**Issue by devilfish707** [patriciogonzalezvivo/glslViewer#322]
when using record command the process crashes randomly with segfault error message in glslviewer console.
 macos 11.6.8 big sur m1, console log: [log.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/10450103/log.txt)

**Comment by patriciogonzalezvivo** [comment]
@devilfish707  shared this video 

https://user-images.githubusercontent.com/346914/213280993-79f3cca8-3d34-4b6d-8a67-7194e5e54e5c.mov

**Comment by patriciogonzalezvivo** [comment]
@devilfish707 thanks for submitting this issue! I will take a look

**Comment by patriciogonzalezvivo** [comment]
Hi! @devilfish707, found a very snarly repression related to GLM SWIZZLES on VERA (a dependency of glslViewer).

I just push a small diff that solved it on my side, Do you mind pulling both `glslViewer` repo and `deps/vera` submodule, recompile and try recreating the issue? 

https://github.com/patriciogonzalezvivo/vera/compare/8492e0fa3521c982bd8a9c848d3fae48a6cf8ca8...cba5d9cb8d9cbe2b1f0c24545ffd6279e8fae3ef#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL7

**Comment by devilfish707** [comment]
hey i build glslViewer with the commit and it seems to work! no more crashes

**Comment by patriciogonzalezvivo** [comment]
That's great news! Thanks for the patience and giving it a go.
