### ISSUE TITLE
Can't compile on macOS (custom FFmpeg install causing issues?)

### ISSUE THREAD

**Issue by sinewave440hz** [patriciogonzalezvivo/glslViewer#324]
Hi. I've previously had glslViewer up and running as per the macOS installation instructions. I've been using glslViewer daily up until the present issue. The issue began when I noticed that the `record` command wasn't working. Apparently I didn't have `ffmpeg` installed (or installed the same way, at least) last time I compiled glslViewer.  Since then, I have begun to use ffmpeg extensively elsewhere and now have a custom-configured local installation that meets my needs and works well (elsewhere). However, when I try and re-compile glslViewer now, my `make` command fails with: `ld: symbol(s) not found for architecture x86_64`. After ruling out a few things, it seems that the problems here are due to the ffmpeg installation in some way. Can I use glslViewer with the latest ffmpeg installed locally?

Here is the cmake output:
[cmakeoutput.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/10675217/cmakeoutput.txt)
And the make output:
[makeoutput.txt](https://github.com/patriciogonzalezvivo/glslViewer/files/10675249/makeoutput.txt)

Ffmpeg works fine in itself.

Unfortunately, after all this, I am getting the seg fault error and can't build to correct it. Is there a way to build without ffmpeg? Obviously it would be nice to have that in but it's more important to be able to use glslViewer at all...

UPDATE: I tried to compile after installing ffmpeg from Homebrew with the same result...so, some recent change in ffmpeg could be the cause. Still can't build though...

**Comment by sinewave440hz** [comment]
Well, I managed to run after installing glslviewer via homebrew instead. Same old problem with being unable to export video at all, but I suppose I can just screen capture the window and do whatever needs to be done separately in ffmpeg. Still, would have been nice though... :)

**Comment by patriciogonzalezvivo** [comment]
Hi! I'm sorry for this issue. Seams that is related to a regression on the code. I will try to give it a try on the next couple of weeks. Thanks for the heads up on it.

**Comment by patriciogonzalezvivo** [comment]
This is related to #322

**Comment by sinewave440hz** [comment]
Thanks @patriciogonzalezvivo. I'm relieved that I can use it in the meantime at least. Thanks for all your great work!

**Comment by patriciogonzalezvivo** [comment]
@sinewave440hz It's ok if I close this one? I will report progress on this other issue thread https://github.com/patriciogonzalezvivo/glslViewer/issues/322

**Comment by sinewave440hz** [comment]
Sounds like a plan! I didn't really recognise it as the same as #322, but I'm sure it's related if you think so :)
