### ISSUE TITLE
Blender addon license

### ISSUE THREAD

**Issue by nguyenvuducthuy** [patriciogonzalezvivo/glslViewer#325]
Hi there,
I have this when I try to use in Blender
![image](https://user-images.githubusercontent.com/11515922/221092194-fdbe8e22-a6f0-48c1-82a9-0cccde180587.png)

**Comment by patriciogonzalezvivo** [comment]
Sorry, ignore that. I just remove that prompt for one that tells you to go to the "Scripts" section and search for `main.frag` and `main.vert`. GlslViewer for the moment don't have exposed properties in that panel. I will work on it on the future.
