### ISSUE TITLE
Blender addon crash when enable render viewmode

### ISSUE THREAD

**Issue by nguyenvuducthuy** [patriciogonzalezvivo/glslViewer#326]
Hi, 
I load the plugin without any error but I have another issue when I try to enable render view mode, Blender crashed ..
![image](https://user-images.githubusercontent.com/11515922/221346815-126c47df-8d9a-46ef-a699-b5c9035b4634.png)

**Comment by nguyenvuducthuy** [comment]
I'm using blender 3.4.1 and python 3.10.0

**Comment by patriciogonzalezvivo** [comment]
Rendering is not implemented yet. I started working on this Blender integration just a week ago. Thanks for the patience

**Comment by patriciogonzalezvivo** [comment]
Seams the spaces on your loaded images produce the crash. I'm pushing a fix that require to pull the latest version of VERA's submodule

**Comment by nguyenvuducthuy** [comment]
Hi thanks to take time for look at that. But it isn't fixing in my end. I will try to find out. I really love this addon, thanks to make it available.
