### ISSUE TITLE
glslViewer does not compile.

### ISSUE THREAD

**Issue by MubinMuhammad** [patriciogonzalezvivo/glslViewer#342]
Why you all haven't included the 'stdint.h' header file in the 'deps/vera/include/vera/ops/pixel.h' I had do to it by myself.

**Comment by droshux** [comment]
I also had this issue, I don't know what the pull request permissions are but if I could I might make this fix tonight.

**Comment by patriciogonzalezvivo** [comment]
Oh, please submit a PR for it. Just for curiosity, what OS are you using?On Jun 8, 2023, at 3:40 AM, droshux ***@***.***> wrote:﻿
I also had this issue, I don't know what the pull request permissions are but if I could I might make this fix tonight.

**Comment by MubinMuhammad** [comment]
Ok, I use Arch Linux, and used CMake to compile it.

**Comment by f-and** [comment]
I'm in the same boat, tried with both the yay install and the wiki instruction and both come to the same error about cstdint.

**Comment by droshux** [comment]
> Oh, please submit a PR for it. Just for curiosity, what OS are you using?On Jun 8, 2023, at 3:40 AM, droshux ***@***.***> wrote:﻿ I also had this issue, I don't know what the pull request permissions are but if I could I might make this fix tonight. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi, sorry for the VERY late reply: There is already a pull request on the vera repository that appears to fix this issue. All checks have passed and there are no conflicts but it doesn't look like it has been merged yet.
https://github.com/patriciogonzalezvivo/vera/pull/4

**Comment by patriciogonzalezvivo** [comment]
OK, I just push the change to the latest VERA. Do you mind?

```
git pull
git submodule update
cd build
make
```

**Comment by MubinMuhammad** [comment]
Sorry for the late reply. But I am using wayland with Arch. Maybe, that is the problem. As in the 'Compile on Linux' section,they told about Compiling glslViewer  on X11. So, maybe a problem with wayland. It would be better if
glslViewer doesn't have that many dependencies though.

**Comment by MubinMuhammad** [comment]
Ok, thank you very much for this change. Really appreciate the response from the owner!
