### ISSUE TITLE
glslViewer looks for libavdevice.so.58, but I have 59 (Debian 12.1)

### ISSUE THREAD

**Issue by bazilmuzik** [patriciogonzalezvivo/glslViewer#346]
When I run the command 
glslViewer xxx.frag
I get the error message 
libavdevice.so.58: cannot open shared object file: No such file or directory
After looking in my OS, I found that I currently have libavdevice.so.59, so it's normal that 58 is not found

Then I tried to add the following line in ld.so.conf (deduced from what I've read in many blogs)
/usr/lib/x86_64-linux-gnu
because that's where libavdevice.so.59 is on my laptop

But I still get the same error message...

Is it possible that glslViewer only expects libavdevice.so.58, but no newer version ? Is there an easy way around that ? Like a glslViewer config file or something ? 

Thanks in advance !

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks for reaching out? What version of glslViewer do you have? It's installed by source? Or through .deb / PPA?

**Comment by bazilmuzik** [comment]
Unfortunately I don't remember how I installed it, but I probably followed the compiling from source procedure here. What I can say for sure is that I installed it when I was on Debian 11, and then updated my OS to Debian 12.1, maybe that's why it's stuck to libavdevice.so.58... Should I maybe uninstall everything and try to install again ?

**Comment by bazilmuzik** [comment]
Ok that was it indeed ! 
I uninstalled glslViewer, recompiled it, and now it works fine :) 
Noted: when compiling from source and updating OS, one needs to recompile !

**Comment by patriciogonzalezvivo** [comment]
That makes sense. 😃 

I'm glad it worked out
