### ISSUE TITLE
3.2.2 win64 Record video rate not being set correctly

### ISSUE THREAD

**Issue by cdavidr1** [patriciogonzalezvivo/glslViewer#347]
![image](https://github.com/patriciogonzalezvivo/glslViewer/assets/123332084/6c4068b4-a986-4cda-a200-7461240f8862)

Tried to run the record command 

glslViewer test.frag -e record,test.gif,0,10,60

Keep getting the same error regardless of anything I try (.mp4 or different numbers)

**Comment by patriciogonzalezvivo** [comment]
Hi! I just push a fix on `vera` that fixes this issue too. Please pull all changes on this repo and submodules and try recompiling
