### ISSUE TITLE
Makefile sets PLATFORM incorrectly for RPi running Ubuntu

### ISSUE THREAD

**Issue by djulien** [patriciogonzalezvivo/glslViewer#37]
I'm running Ubuntu MATE on RPi, which causes the Makefile to select PLATFORM_LINUX instead of PLATFORM_RPI.  This causes an init error when I try to run glslViewer (not running XWindows).

Just checking the OS is not enough to identify a RPi in this case.  I'm not sure what the most appropriate check would be - should it use something like "uname -m" or "uname -p" to check for an ARM CPU, or is there a more reliable way to detect a RPi?

If I force PLATFORM_RPI, then it compiles and runs okay without XWindows running.

**Comment by patriciogonzalezvivo** [comment]
Hi! Never use that distro, it have `/opt/vc/` folder?
Maybe we can use them as a way to detect it it's in a raspberry Pi or not

**Comment by djulien** [comment]
Yes, it has the /opt/vc folder.  It was installed during some setup steps.

That is a good way to check for RPi.  Do you want a PR, or just leave it as info?  (I wasn't sure if anybody else would like the change)

**Comment by patriciogonzalezvivo** [comment]
could you make a PR?

Thanks!
