### ISSUE TITLE
add shadertoy support

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#41]
I would like to add simple support for shadertoy image shaders:
* if iGlobalTime is referenced, define the iGlobalTime uniform
* if iResolution is referenced, define the iResolution uniform
* if mainImage is defined, define a main() function that calls it

Shadertoy scripts are recognized automatically based on their content, not by a command line flag.

If I get this working, are you interested in a pull request for this change?

**Comment by patriciogonzalezvivo** [comment]
Yes, definitely. How do you think on checking for style shadertoy code.
In the case is a shadertoy code... and only in that case...  add some `#define iGlobalTime u_time` and `#define iResolution u_resolution` and the `mainImage()` wrapper... right?

I'm thinking on keeping it simple and altogether in one part of the code.... so is easy to maintain. Also we avoid adding extra drivers calls with extra uniforms.

**Comment by doug-moen** [comment]
I implemented iResolution, iGlobalTime, iTimeDelta, iDate and iMouse.
@patriciogonzalezvivo merged pull request #43, and I'm done for now.
