### ISSUE TITLE
Print shader statistics on load

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#47]
When the user's shader program is loaded, I'd like to print some statistics.
Specifically, the load time in seconds, and the program size or number of instructions.

This provides a rough metric of how expensive the shader is, and is useful if you are trying to optimize a shader by making it load or run faster.

I've got an initial prototype of this. Are you interested in a pull request?
The output looks something like this (on stderr):
```
shader load time: 2.71828s size: 108242
```

**Comment by patriciogonzalezvivo** [comment]
sure! The load time is the time it took to compile? what's the size of? 
For benchmarking I add in the console IN/OUT interaction the posibility to "ask" for uniform states... specially useful for 'u_delta'. Check this python class I use for it https://github.com/tangrams/blocks/blob/gh-pages/shader.py

**Comment by doug-moen** [comment]
The load time is the elapsed time for compiling the fragment and vertex shaders and linking them into a program. The size is currently the size of the linked program in bytes. There's an API for getting an instruction count, but when I call it, it fails.

So this one line of text gets printed to stderr on initial load, and then each time a shader is reloaded when a file changes.

Thanks for the python program. I can also get delta manually by typing "delta" into the terminal program from which I run glslViewer.

**Comment by patriciogonzalezvivo** [comment]
the load time and size seams great addition, thanks
