### ISSUE TITLE
u_view2d

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#50]
Check out my new PR #49. It introduces a new uniform, `u_view2d`, a transform matrix which is used by a fragment shader to pan and zoom around in a 2D scene.

The best way to understand it is to compile the program then run examples/mandelbrot.frag.
Use left-mouse-button drag to pan around, and use the mouse scroll wheel or multi-touch trackpad to zoom in and out. Then look at the source code for mandelbrot.frag to see how u_view2d is used.

**Comment by patriciogonzalezvivo** [comment]
any chance of adding rotation on Z to it? if we are going to support it long term let's make the most of it... right?

**Comment by doug-moen** [comment]
Yes, I would like to add rotation using the right mouse button. I spent 2
days on the PR for just pan and zoom, and I wanted to get that finished
before taking on more work. (First, do the minimum viable product (MVP),
then extend it later.) I also considered using the Home key on the keyboard
to return to the initial view, but I don't know if that's possible since
you are reading variable names from stdin already.
