### ISSUE TITLE
 error: use of undeclared identifier GL_PROGRAM_BINARY_LENGTH

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/glslViewer#53]
@doug-moen glslViewer is not compiling on osx after this https://github.com/patriciogonzalezvivo/glslViewer/blame/master/src/gl/shader.cpp#L112 

Could you take a look to it.

<img width="719" alt="screen shot 2017-02-17 at 4 37 12 pm" src="https://cloud.githubusercontent.com/assets/346914/23084391/0eef7498-f530-11e6-8373-afd4014ccbc7.png">

**Comment by patriciogonzalezvivo** [comment]
Same for Raspberry Pi... plus GL_PROGRAM_INSTRUCTIONS_ARB 

<img width="990" alt="screen shot 2017-02-17 at 5 08 45 pm" src="https://cloud.githubusercontent.com/assets/346914/23085106/c51468ac-f533-11e6-9037-19ca3e2153ea.png">

Are we sure this are OpenGL ES 2. commands??

**Comment by patriciogonzalezvivo** [comment]
I solve it for OSX doing: https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/gl/gl.h#L2

And for RaspberryPi by doing:
https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/gl/shader.cpp#L109-L122

I'm not sure this is part of OpenGL ES 2.0, I believe GLFW is using OpenGL... because is available on desktop.

**Comment by doug-moen** [comment]
Here's another solution:
```
    #ifdef GL_PROGRAM_BINARY_LENGTH
            GLint proglen = 0;
            glGetProgramiv(m_program, GL_PROGRAM_BINARY_LENGTH, &proglen);
            if (proglen > 0)
                std::cerr << " size: " << proglen;
    #endif
    #ifdef GL_PROGRAM_INSTRUCTIONS_ARB
            GLint icount = 0;
            glGetProgramivARB(m_program, GL_PROGRAM_INSTRUCTIONS_ARB, &icount);
            if (icount > 0)
                std::cerr << " #instructions: " << icount;
    #endif
```
Sorry about making a mess. I am a decent programmer, but this is my first time using OpenGL. The  way the API is different on every platform and GPU driver is a bit dismaying. Apparently these "iv"s are not part of OpenGL ES 2.0.

**Comment by patriciogonzalezvivo** [comment]
That's a great idea! I will change it.
oh plis don't worry, we are all here to learn!

**Comment by patriciogonzalezvivo** [comment]
Following @doug-moen suggestions here https://github.com/patriciogonzalezvivo/glslViewer/commit/a8c4e986e20e2dec83d06c3964c5cecea3ce1b5f
