### ISSUE TITLE
Mandelbrot and "__" macros

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/glslViewer#56]
Hi @doug-moen, I'm getting this error msg on Ubuntu 16.10 64bits together with bad performance on Mandelbrot example

```
Warnings while compiling examples/mandelbrot.frag:
0:1(9): preprocessor warning: Macro names containing "__" are reserved for use by the implementation.
```
<img width="1238" alt="screen shot 2017-02-21 at 11 46 49 am" src="https://cloud.githubusercontent.com/assets/346914/23174853/b14c80a2-f82b-11e6-9d33-0cabed281791.png">

**Comment by doug-moen** [comment]
I just synced your changes and rebuilt. Looks like you already fixed the __ bug.

As for bad performance of mandelbrot, I can't replicate that, I'm still getting 60fps on my GTX 1050 with 640 cores. 😊  The RPI has, what, 4 cores? I'm sure the code can be made faster. I'll need to get an RPI before I can investigate that.

**Comment by patriciogonzalezvivo** [comment]
I'm not sure what's happening on that mandelbrot example that looks so bad in ubuntu... It's running in a VM but hardware acceleration is turn on, so should be using my Nvidia card... more weirdly... all other examples seams to work.

As you said, in the raspberry pi doesn't work at all... which make sense

**Comment by doug-moen** [comment]
It's running in a VM. Are you sure that it is hardware accelerated? The
frame rate suggests no. I understand that this can be tricky to set up,
depending on your environment.

**Comment by patriciogonzalezvivo** [comment]
Well... is had to know my this said it is...

<img width="1449" alt="screen shot 2017-02-21 at 2 06 31 pm" src="https://cloud.githubusercontent.com/assets/346914/23180306/fc492124-f83e-11e6-96fd-d98a5b16ca59.png">

Other shaders work well...

<img width="1483" alt="screen shot 2017-02-21 at 2 07 16 pm" src="https://cloud.githubusercontent.com/assets/346914/23180348/21113172-f83f-11e6-871c-c3648cb206cb.png">

it's a strange result the one is producing... everything else seams to be working perfectly : ) I'm thinking on making a 1.1 release soon with all these sweet improvements : ) (if you are ok w it)

**Comment by doug-moen** [comment]
The mandelbrot program is quite simple, but it has a loop that iterates 100 times. I think early GPUs didn't support loops, and there are tricks involved in implementing them. So maybe this loop has too many iterations? Maybe you can try smaller values of maxiter. See if you can find the largest value of maxiter that works correctly?

Obviously something isn't working, but I can't reproduce the problem locally. There is no red, so the colour calculation isn't working. If the GPU driver aborts the loop before reaching the exit condition, the colour won't be calculated, so maybe?

**Comment by patriciogonzalezvivo** [comment]
wowo this is weird... in this other distro (PIXEL i386) works... : /

This is odd


<img width="861" alt="screen shot 2017-02-21 at 2 50 00 pm" src="https://cloud.githubusercontent.com/assets/346914/23182094/5b108642-f845-11e6-911a-f164215ec5b8.png">

Wonder why?
