### ISSUE TITLE
Errors on RPI

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/glslViewer#57]
@doug-moen This is happening on RPI:

```
CompiledWarnings while compiling examples/test.frag:
CompiledError linking shader: ERROR:PREPROCESSOR-1 (fragment shader, line 1) Preprocessor syntax error : reserved macro name
1: #ifdef GL_ES
Warnings while compiling shader:
CompiledWarnings while compiling shader:
Compiled
```

<img width="898" alt="screen shot 2017-02-21 at 12 10 16 pm" src="https://cloud.githubusercontent.com/assets/346914/23175893/dcafe114-f82e-11e6-8e22-9137e7a8fd83.png">

**Comment by patriciogonzalezvivo** [comment]
Fixing this and https://github.com/patriciogonzalezvivo/glslViewer/issues/56 in this commit https://github.com/patriciogonzalezvivo/glslViewer/commit/118a32ad6f9764ecaf430bf82431c86545468d1b

Still getting an annoying `Compiled` text before every line... : / 

```bash
[~/glslviewer-1.1]$ glslViewer examples/test.frag                                                                                                                                                                                                                    *[master] 
Warnings while compiling shader:
CompiledWarnings while compiling examples/test.frag:
Compiledshader load time: 0.00132296s
Warnings while compiling shader:
CompiledWarnings while compiling shader:
Compiled
```

Any idea where is coming from?

**Comment by doug-moen** [comment]
The string "Compiled" does not occur anywhere in the glslViewer source code.

According to this forum, it's coming from the OpenGL driver on the RPI:
https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=15025

We could add code to Shader::compileShader to check if the shader info log consists of "Compiled" and nothing else: if so, ignore the log.

**Comment by patriciogonzalezvivo** [comment]
haaa nice catch! I add a `std::endl` at the end of it... 

: )
