### ISSUE TITLE
GLFW init failed

### ISSUE THREAD

**Issue by suhr** [patriciogonzalezvivo/glslViewer#58]
```
% glslViewer examples/test.frag
ABORT: GLFW init failed
```

**Comment by patriciogonzalezvivo** [comment]
Hi, please provide more information about what system are you running it on

**Comment by suhr** [comment]
OS: Linux
GLFW version: 3.2.1
OpenGL renderer string: Gallium 0.4 on AMD JUNIPER (DRM 2.43.0 / 4.6.3-gentoo, LLVM 3.8.0)

**Comment by patriciogonzalezvivo** [comment]
did you compile? or are you using a binary?

**Comment by suhr** [comment]
I did compile it.

**Comment by doug-moen** [comment]
PR #60 will provide some additional diagnostics to help identify the problem.

**Comment by suhr** [comment]
Thanks to PR #60, I know what was wrong. When GLFW is compiled with `wayland` flag, it expects Wayland display, and if there's none, it doesn't fallback to X.

Closing, since this is not really a glslViewer issue.
