### ISSUE TITLE
MakeFile error on osx

### ISSUE THREAD

**Issue by JoshuaBatty** [patriciogonzalezvivo/glslViewer#6]
Hi Patricio, 

I have installed homebrew and glfw as per your instructions for osx but when I get to the make command I am getting the following error. Any ideas how to resolve this? Thanks :)

Joshuas-MBP:glslViewer josh$ make
make: pkg-config: Command not found
src/main.o
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/main.cpp -o src/main.o -Wno-deprecated-declarations
make: pkg-config: Command not found
src/shader.o
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/shader.cpp -o src/shader.o -Wno-deprecated-declarations
make: pkg-config: Command not found
src/texture.o
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/texture.cpp -o src/texture.o -Wno-deprecated-declarations
make: pkg-config: Command not found
src/vboMesh.o
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/vboMesh.cpp -o src/vboMesh.o -Wno-deprecated-declarations
make: pkg-config: Command not found
src/vertexLayout.o
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/vertexLayout.cpp -o src/vertexLayout.o -Wno-deprecated-declarations
make: pkg-config: Command not found
make: pkg-config: Command not found
g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ src/main.o src/shader.o src/texture.o src/vboMesh.o src/vertexLayout.o -lfreeimage -framework OpenGL  -L/usr/local/lib/ -o glslViewer
Undefined symbols for architecture x86_64:
  "_glfwCreateWindow", referenced from:
      initGL(int, char**) in main.o
  "_glfwGetFramebufferSize", referenced from:
      fixDpiScale() in main.o
  "_glfwGetMouseButton", referenced from:
      handleCursor(GLFWwindow*, double, double) in main.o
  "_glfwGetWindowSize", referenced from:
      fixDpiScale() in main.o
  "_glfwInit", referenced from:
      initGL(int, char**) in main.o
  "_glfwMakeContextCurrent", referenced from:
      initGL(int, char**) in main.o
  "_glfwPollEvents", referenced from:
      updateGL() in main.o
  "_glfwSetCursorPosCallback", referenced from:
      initGL(int, char**) in main.o
  "_glfwSetKeyCallback", referenced from:
      initGL(int, char**) in main.o
  "_glfwSetWindowShouldClose", referenced from:
      handleKeypress(GLFWwindow*, int, int, int, int) in main.o
  "_glfwSetWindowSizeCallback", referenced from:
      initGL(int, char**) in main.o
  "_glfwSwapBuffers", referenced from:
      renderGL() in main.o
  "_glfwTerminate", referenced from:
      initGL(int, char**) in main.o
      closeGL() in main.o
  "_glfwWindowShouldClose", referenced from:
      isGL() in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [glslViewer] Error 1

**Comment by karimnaaji** [comment]
hey! `brew install pkg-config` should fix that!

**Comment by JoshuaBatty** [comment]
Brilliant got it to work, Thanks!
