### ISSUE TITLE
Feature request: User specify max FPS

### ISSUE THREAD

**Issue by ebrensi** [patriciogonzalezvivo/glslViewer#66]
I notice the fan of my laptop starts working hard when I bring up glslViewer.   I think the GPU/CPU or something is doing more work than it needs to.  Much of what I do does not really require a new frame every 1/60 of a second.  It would be nice to have a FPS limiter.

**Comment by pldiiw** [comment]
I know it's old, but for future reference, you can use this to cap the FPS rate: https://github.com/torkel104/libstrangle

**Comment by patriciogonzalezvivo** [comment]
hi. Sorry for the long time. you know I can find libstrangle?

**Comment by doug-moen** [comment]
https://gitlab.com/torkel104/libstrangle

**Comment by patriciogonzalezvivo** [comment]
Feature added! Use the argument --fps <number>
