### ISSUE TITLE
u_mouse values off by about half the normalized coordinate space

### ISSUE THREAD

**Issue by tambarskjelve** [patriciogonzalezvivo/glslViewer#68]
The following snippet works perfectly well in the online editor as well as shadertoy:

```
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform vec2 u_mouse;
uniform float u_time;

void main() {
    
    vec2 st = gl_FragCoord.xy/u_resolution.xy;
    vec2 normouse = u_mouse.xy / u_resolution.xy;
    
    gl_FragColor = vec4(0.0,0.0,1.0,0.5);
    
    if (normouse.x < st.x) {
        gl_FragColor = vec4(1.0,0.0,0.0,0.5);
    }
    
    if (normouse.y < st.y) {
        gl_FragColor = vec4(0.0,1.0,0.0,0.5);
    }   
}
```

In glslViewer however, the x-coordinate only works for half the screen, and the y-coordinates seems to by off by about 0.5 (normalized), only filling half the screen when the mouse reaches the top of the window. I'm testing on a 2016 MacBook Pro, with the screen scaled down a bit.

**Comment by Sdaniele** [comment]
+ 1 on MacBook Pro running 10.12.6 (16G29)

**Comment by patriciogonzalezvivo** [comment]
Seams like a pixel density problem

**Comment by Sdaniele** [comment]
yes, it has to do with Apples HIDPI Mode: tried it on a non HiDPI Monitor and it works fine.

**Comment by patriciogonzalezvivo** [comment]
Mmm... I though I fixed this here https://github.com/patriciogonzalezvivo/glslViewer/blob/master/src/app.cpp#L474 ...
Could you investigate a little more?

**Comment by tambarskjelve** [comment]
Recompiled just now, issue persists.

**Comment by patriciogonzalezvivo** [comment]
yes... I didn't change nothing on the code.
It was an old issue I thought was solve.

**Comment by Sdaniele** [comment]
ok just thinking loud:
The y offset can be fixed by changing the order of offset and multiply by fPixelDensity in glfwSetCursorPosCallback

so doing in line ~249
            y = viewport.w - y;
            x *= fPixelDensity;
            y *= fPixelDensity; 

fixes the offset... but now there is a clamping happening both on x,y as if the viewport range is not scaled correctly (like somewhere missing a "* fPixelDensity").

sorry I am not a software developer…

**Comment by Sdaniele** [comment]
oh just found it on line 270

            if (mouse.x > viewport.z*fPixelDensity) mouse.x = viewport.z*fPixelDensity;
            if (mouse.y > viewport.w*fPixelDensity) mouse.y = viewport.w*fPixelDensity;

but I am not sure if this fix is correct, as it seems that the viewport is not setup correctly

**Comment by Sdaniele** [comment]
ok I have a fix now,

**Comment by jcksncllwy** [comment]
@Sdaniele Could you post your fix? I'm running into this issue as well

**Comment by Sdaniele** [comment]
Done

**Comment by patriciogonzalezvivo** [comment]
Thanks!
