### ISSUE TITLE
View3d: A viewer for ray-marched 3D shapes

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#70]
Suppose you create a 3D scene in a fragment shader, using Function
Representation and ray-marching instead of polygons, as seen on shadertoy.com.

For this use case, I have created a 3D browser that allows you to pan, zoom,
and rotate the 3D scene, using the mouse. See PR #69.

The fragment shader uses 3 uniform variables:

  uniform vec3 u_eye3d;
  uniform vec3 u_centre3d;
  uniform vec3 u_up3d;

These are the same quantities that are passed to the lookAt function in GLM
and other libraries.

See the examples menger.frag and raymarch.frag.
These are lightly modified Inigo Quilez demos from shadertoy.com.
Using the viewer, you can fly around and view these models from every perspective.
Eg, you can fly inside the menger sponge, something you can't do with the shadertoy version.

The user interface uses the scroll wheel for zoom, left-button for rotate,
and right-button for pan.

I'd appreciate feedback on the design and the UI.

**Comment by patriciogonzalezvivo** [comment]
Hi @doug-moen I add space holders on the README.md so we can document this new uniforms. Could you add them?

I also add you to the README.md feel free to point to your website and add some extra data
