### ISSUE TITLE
non-interactive PNG output

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#71]
I would like
```
   glslViewer --headless -o foo.png foo.frag
```
to create a PNG file and exit immediately. Currently, it pauses forever, without opening an OpenGL window.

I've implemented this in a local workspace. Will you accept a pull request for this?

**Comment by patriciogonzalezvivo** [comment]
You need to set the exit time with -s [seconds] I suggest using 0.5 or 1

**Comment by doug-moen** [comment]
Yes, I could do that, but it adds an unnecessary delay. Is there a use case for `--headless` without setting an exit time?

My code change is this:
```
@@ -314,7 +316,7 @@ int main(int argc, char **argv){
         // Swap the buffers
         renderGL();
 
-        if (timeLimit > 0.0 && getTime() > timeLimit) {
+        if (headless || (timeLimit > 0.0 && getTime() > timeLimit)) {
             bRun.store(false);
         }
     }
```
So, `--headless` renders 1 frame then exits. Does this break anything?

**Comment by doug-moen** [comment]
I suppose that could interfere with a fragment shader using the back buffer, where you legitimately need to compute multiple frames before dumping an image.

What I want is a way to dump an image and exit after rendering the first frame.
How about if I make a change so that I can use the following syntax:
```
glslViewer --headless -s 0 -o foo.png foo.frag
```
So I am redefining '-s 0' to mean "exit after rendering the first frame". Currently that option has no effect. Sound reasonable?

**Comment by patriciogonzalezvivo** [comment]
Yes, I usually do headless with out exit for benchmarking
