### ISSUE TITLE
system freeze with Intel graphics on Linux

### ISSUE THREAD

**Issue by doug-moen** [patriciogonzalezvivo/glslViewer#73]
I switched my Ubuntu 16.04 system to Intel graphics (for testing purposes). Slow, complicated shader programs work fine in glslViewer. But short, simple shader programs cause the desktop UI to freeze, requiring a reboot.

For example, here's the shadertoy.com "hello world" program:

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
vec2 uv = fragCoord.xy / iResolution.xy;
fragColor = vec4(uv,0.5+0.5*sin(iGlobalTime),1.0);
}

This program runs fine on the shadertoy.com website, inside Firefox. But give the same program to glslViewer and we need to reboot. The problem, apparently, is that glslViewer runs shader programs at max frame rate, with no throttling. If the shader program is too simple and fast, then BOOM.

**Comment by doug-moen** [comment]
Adding a 10 millisecond sleep before calling glfwSwapBuffers() makes the bug go away. This just validates my hypothesis, not saying this is the final fix.

**Comment by doug-moen** [comment]
@patriciogonzalezvivo: My proposal is to implement a 60 FPS framerate limit. Will you accept that?

**Comment by patriciogonzalezvivo** [comment]
let's do! I think someone else made that call to https://github.com/patriciogonzalezvivo/glslViewer/issues/66.

Thanks!

**Comment by patriciogonzalezvivo** [comment]
Any thing I can help with this @doug-moen ?

**Comment by doug-moen** [comment]
Calling glfwSwapInterval(n) with n > 1 might be an easy way to slow down
the frame rate even further, for people who have requested a way to reduce
GPU power consumption on a laptop.

I just tested this. On a shader that normally runs at 60 FPS,
`glfwSwapInterval(2);` slows it down to 30 FPS.

**Comment by doug-moen** [comment]
Still researching this. I found a comment on a forum thread discussing
glfwSwapInterval.

> I noticed that on a crappy laptop with integrated Intel graphics I can't
enable v-sync. Presumably a driver problem, but I've never bothered to
update to see if it fixed the problem.
>
https://www.opengl.org/discussion_boards/showthread.php/177446-glfwSwapInterval()-and-glfwSwapBuffer()-Questions

Here's a comment relating to the Intel driver on Windows: "I actually have
this same issue (running a Intel HD 4400 on a Insperion 3542). I can't get
vsync to work unless I have it forced in the drivers menu. If I have it set
to "Application Settings" I get screen tearing, even though mednafen has it
turned on (video.glvsync 1)."

> https://forum.fobby.net/index.php?t=msg&goto=4047&

These posts suggest that calling glfwSwapInterval(1) may not fix the bug.

On 17 August 2018 at 12:42, Patricio Gonzalez Vivo <notifications@github.com

**Comment by doug-moen** [comment]
I'm not using the glslViewer project any more (I copied and pasted some of
your code into my own app instead, because I need OpenGL object sharing
between glslViewer contexts and contexts I create in my own code). I'm too
busy to contribute code right now, but I'm sharing information that I think
you might find useful.

I now realize that I can't make the glslViewer code work correctly on all
GPU drivers, because some bugs are too severe to work around. So my new
policy is, I'm willing to provide mitigations to work around driver bugs,
as long as the code required is simple (eg, numeric parameters that
configure GPU driver behaviour). I haven't looked at libstrangle, but it
might be too complicated for the value it delivers, at least for me.

What I'm now considering for Curv is: a numeric parameter to configure
glfwSwapInterval, and another parameter, # of milliseconds to sleep before
calling glfwSwapBuffers.

The real solution to reducing GPU power consumption is to only render a new
frame if something changes. If the model isn't animated, then new frames
are only rendered if you are interacting with the model, eg rotating a 3D
model with the mouse, or manipulating a slider to change a uniform
variable. Maybe that could be made to work in glslVIewer as well? Only
render a frame if a uniform variable has changed. If the shader doesn't
reference any uniform variables that change every frame, like u_time, then
power consumption will go way down.

**Comment by patriciogonzalezvivo** [comment]
Hi @doug-moen ! I'm happy to hear that Curv keeps growing healthy.  Congratulations.

Yeah.. I'm going to make some core changes to flag changes better...
Hopefully that with glfwSwapInterval(1) will help. But generally I agree with your policy.
