### ISSUE TITLE
shader from shadertoy with iChannel0 get error

### ISSUE THREAD

**Issue by wzyzb** [patriciogonzalezvivo/glslViewer#74]

**Comment by doug-moen** [comment]
I did the shadertoy support. We don't support the full set of shadertoy uniforms yet.
However, new volunteers for implementing this stuff are welcome.

**Comment by patriciogonzalezvivo** [comment]
This is part of a bigger discussion about if we want to fully support ShaderToy examples, they move fast, and in this process they change specs (for example now they are using webgl 2.0 so all texture calls are done through `texture()` function and not longer the `texture2D()` one). They can handle that internally by replacing code. But for us keep parity with OpenGL ES 2.0 is only getting harder. Shaders directly imported from ShaderToy are going to fail only more and more
