### ISSUE TITLE
GLFW/glfw3.h file not found

### ISSUE THREAD

**Issue by jeffThompson** [patriciogonzalezvivo/glslViewer#8]
(First, wow: this document is super amazing. Thank you!)

I'm trying to install the examples using the Mac instructions. But when using the `make` command I get the following error:

    Package glfw3 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `glfw3.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'glfw3' found
    src/main.o
    g++ -Wall -g -std=c++0x -fpermissive -DPLATFORM_OSX -stdlib=libc++  -I/usr/local/include/ -Isrc/ -I//Library/Frameworks/GLUI.framework -g -c src/main.cpp -o src/main.o -Wno-deprecated-declarations
    In file included from src/main.cpp:11:
    In file included from src/platform.h:8:
    src/gl.h:4:10: fatal error: 'GLFW/glfw3.h' file not found

Not sure if this is an error with my setup, or with the code :)

**Comment by patriciogonzalezvivo** [comment]
have you install glfw3 properly?
