### ISSUE TITLE
Add support for #version directive

### ISSUE THREAD

**Issue by SE2Dev** [patriciogonzalezvivo/glslViewer#85]
Currently I'm unable to test any shaders that contain a `#version` directive due to the following error, even if the `#version` statement is made at the very beginning of the file:
```
Errors while compiling fragment shader:
0(2) : error C0204: version directive must be first statement and may not be repeated
```

Additionally, I've confirmed that I am indeed using a proper OpenGL 4.x context.

Upon further investigation, I've found that because `Shader::compileShader()` appends a prologue to the shader, the version statement will never truly be at the beginning of the file.

**Comment by blaze33** [comment]
This was answered in: https://github.com/patriciogonzalezvivo/glslViewer/issues/67
