### ISSUE TITLE
Raspberry Pi - error while loading shared libraries: libGLESv2.so

### ISSUE THREAD

**Issue by davidreyburn** [patriciogonzalezvivo/glslViewer#86]
I am attempting to get glslViewer up and running on my raspberry pi 3, however when I run apt-get install glslviewer and then attempt to run a test frag, I get the above result. I have tried increasing GPU memory, enabling GL drivers in raspi-config, and installing a few different openGL packages I could find, but nothing works. Just running a glslViewer command with no argument will get the same message as well.

Is there a step I'm missing here?

Full error is:

glslViewer: error while loading shared libraries: libGLESv2.so: cannot open shared object file: No such file or directory

**Comment by patriciogonzalezvivo** [comment]
Hi! seams Raspbian had change the name of their broadcom versions of libEGL.so and libGLESv2. to libbrcmEGL.so and libbrcmGLESv2.so.

: /

I haven't made a fix for it yet. This change shouldn't affect old versions of Raspbian

**Comment by davidreyburn** [comment]
Thanks for the info! I installed Raspbian Jesse and confirmed that it's working as expected. Very excited to get started. 

However, I noticed that enabling the GL drivers in raspi-config causes glslViewer to not run, along with some other error messages. Does this mean that glslViewer does not yet take advantage to the Raspberry Pi's graphics hardware acceleration?

**Comment by frenchfaso** [comment]
@davidreyburn I think it's because glslViewer uses the original OpenGL ES driver of the Raspberry Pi and not the newer (but still buggy) OpenGL Desktop driver.

**Comment by frenchfaso** [comment]
@patriciogonzalezvivo thank you so much for your "Book of shaders" it's by far the best resource about shader programming that has ever been written!
It's the book/tutorial I was waiting for, a gentle, fascinating (but complete) introduction (and some) on shader programming.

**Comment by patriciogonzalezvivo** [comment]
Thanks @frenchfaso! 
This issue should be resolve already! Also glslViewer is now part of the new raspbian distribution... so by doing `sudo apt-get install glslViewer` should work
