### ISSUE TITLE
Can't compile on Kali Linux

### ISSUE THREAD

**Issue by kikendo** [patriciogonzalezvivo/glslViewer#91]
I tried to make this work in Kali Linux but doesn't seem to compile.
Kali is based on Debian, yet, I have no idea how this should work.

Any ideas?

**Comment by patriciogonzalezvivo** [comment]
Hi! I did successfully compile it on Kali... you just need to compile and install glfw3 before hands, just like the README.md said for Ubuntu.

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git-core cmake xorg-dev libglu1-mesa-dev
cd ~
git clone https://github.com/glfw/glfw.git
cd glfw
cmake .
make
sudo make install
```

**Comment by kikendo** [comment]
Hmm I followed different instructions, these: 
`Installing on Ubuntu

Install the GLFW 3 library and other dependencies:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libglfw3-dev git-core
Download the glslViewer code, compile and install:

git clone http://github.com/patriciogonzalezvivo/glslViewer
cd glslViewer
make
sudo make install`
These are the ones available on your main page here. Are they wrong?

**Comment by patriciogonzalezvivo** [comment]
If you keep reading the same documentation you mention, it said that not all distributions comes with libglfw3-dev... I belive that's the case of Kali.

In that case you have to install first glfw3 your self

"
These instructions may not work for all users. For example, it seems that libglfw3-dev conflicts with the older libglfw-dev. The previous Ubuntu install instructions direct you to download and compile glfw3 manually:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git-core cmake xorg-dev libglu1-mesa-dev
cd ~
git clone https://github.com/glfw/glfw.git
cd glfw
cmake .
make
sudo make install
"

**Comment by kikendo** [comment]
Hmm yeah I read through, but  got very confused and did it wrong, obviously. Thanks for the clarification, I'll give it a try and see what happens!
