### ISSUE TITLE
Console IN Commands + Rendering Question

### ISSUE THREAD

**Issue by polarianpro** [patriciogonzalezvivo/glslViewer#92]
I just started using this plug-in for sublime text 3 and I love it already! However, I ran into an issue I was hoping someone could help me with.

Where are the png sequences saved after rendering in headless mode? After entering the command it returns:
// Will exit in 1 seconds.
// Will save screenshot to TestRender.png on exit.
// Screenshot saved to TestRender.png

However, when I search my computer for TestRender.png it is no where to be found.

Thank you for any assistance that can be provided.

**Comment by patriciogonzalezvivo** [comment]
Hi @polarianpro! I'm glad you are using it and you are happy with it.
I haven't touch that pluging for a while (https://github.com/patriciogonzalezvivo/sublime-glslViewer). I add the console IN commands way after that plugin... I should dedicate some time to update it. If you want to use the console commands I recommend you running glslViewer directly from the console. glslViewer will reload the shader every time you change it regarding what editor are you using. By running it through the terminal you can use the commands with no problem.

About the gif, there is different ways to do this:

- Run this script I made a while ago https://gist.github.com/patriciogonzalezvivo/7d491ad543fd8f08d6d22c3f3181729e It runs glslViewer several times (one per each frame) then it compose a gif using image magic

- you can make your own python script that use this wrapper I made https://github.com/patriciogonzalezvivo/glslViewer/blob/master/examples/GlslViewer.py to in a same glslViewer instance change a `time` uniform (with the . setUniform(name, vale) method) and take a 'screenshot' of that frame (with the . screenshot(file_name) method). The you can compose them into a single gif using image magic

- If all that is to painful you can use editor.thebookofshaders.com which is an online version of https://github.com/patriciogonzalezvivo/glslEditor (which use https://github.com/patriciogonzalezvivo/glslCanvas) to "Record" (red button in the viewport) a video of it and then transform it to gif with any software like GIF Brewery. Note that glslEditor can be also run natively through electron. 

Hope this have been helpful. Please let me know how this project goes and share your experience online with others. I'm excited to see how more people use glslViewer as a swiss army tool for GLSL shaders : )

All the best,

Patricio

**Comment by polarianpro** [comment]
Thank you for the incredible response! I will play around with the scripts you shared and see what I can come up with. Previously I had been using a combination of HTML5 and Javascript paired with the ThreeJS and CCapture library. However, this is much better because now I do not have to save sublime and refresh the browser every time I want to see the result of changes.
