### ISSUE TITLE
Add uniform and assign its value

### ISSUE THREAD

**Issue by DipenBhagat** [patriciogonzalezvivo/glslViewer#98]
How can i add extra uniform variable and assign its value in ubantu?

**Comment by gregersn** [comment]
At least on Mac, it seems like the uniform values are not updated in the shader unless the shader-file is saved again. 
So updating e.g. u_temp from the interface or via pipe does not change the color when the shader is running, untill temp.frag is changed and saved.

**Comment by patriciogonzalezvivo** [comment]
Nice spot! This should fix it https://github.com/patriciogonzalezvivo/glslViewer/commit/c05c18cfc958b7ced3b36610704f1b3f4a1bc86e

Please pull and recompile.
