### ISSUE TITLE
-D option usage?

### ISSUE THREAD

**Issue by efairbanks** [patriciogonzalezvivo/glslViewer#99]
It seems like `#define MY_DEFINE 100` would translate to `glslViewer mything.frag -D MY_DEFINE 100`, but this does not work. Am I using this incorrectly, or is this broken?

**Comment by patriciogonzalezvivo** [comment]
Hi! thanks for the patience.
The intended use follows the specs used on compilers like gcc, to set up flags (with no values assigned)

Please take a look to the README.md where it said:

"
-D[define] add system #defines directly from the console argument
"

Note that there is no space between the `-D` and the name of the define flag, just like the gcc compiler
